### ISSUE TITLE
ocsms with signal

### ISSUE THREAD

**Issue by Vaear** [nerzhul/ocsms#100]
Hello, i was wondering if it is possible to make this work with the Signal sms app from Open Whisper systems? I can't make it sync from Signal atleast, it only picks the sms that are in the stock app that came with CM12.1 in my case.

**Comment by nerzhul** [comment]
hi @Vaear if you want to support this, i think you could help by providing a patch adding a provider on the owncloud sms app repository.
I close this issue because it's not related with ocsms server backend
