### ISSUE TITLE
SYSTEM ressources overloaded by "DELETE FROM ocsms_smsdatas ..." queries

### ISSUE THREAD

**Issue by Jef2i** [nerzhul/ocsms#102]
## App Context :
Hardware  : NAS Synology
OwnCloud : custom (ie. not from Syno apps) install of v8.1.3
DB backend : internal PostgreSQL
OCSMS server-side : v1.6.0
OCSMS android app : v0.18.5 (from f-droid)

## Usage Context :
.more than one year since OC is installed and running quite fine
.more than six months since OCSMS is installed. Updates by disabling the app, then replacing the folder app then reenabling the app
. 1rst I've exported all my SMS from my smarphone
. client's side I've setup the sync ONLY through wifi (push disabled but this doesn't seem to be taken into account but this is another question)

### System :
Since a while now (several months) I've one system process consuming 25% of my CPU
`  PID PPID USER     STAT   VSZ %MEM %CPU COMMAND`
`15252 11822 postgres R    38244  1.2 24.8 postgres: owncloud owncloud 127.0.0.1(54065) DELETE`
then another one queued
`  PID PPID USER     STAT   VSZ %MEM %CPU COMMAND`
`15441 11822 postgres S    38308  1.2  0.0 postgres: owncloud owncloud 127.0.0.1(54091) DELETE waiting`
then a bit later another one
an so on...
Right now I've got 20 (almost) processes waiting like this.
The phenomenon comes again if I reboot the NAS.

### PostgreSQL
I'm investigating a bit into the DB.
Those queries (obiously, else I would not have posted here !) concern OCSMS
Here is the query :
`DELETE FROM oc_ocsms_smsdatas WHERE user_id = $1 AND sms_id = $2`
20 times !

If I browse the DB's stored data I also note a strange thing.
Some of the most recent (today) SMS added (regarding the "added" field) are old ones.
Furthermore "added" field equals "lastmodified" field value ...

## How to reproduce
* Send or receive or delete an SMS
* connect to internet
* let OCSMS do the sync.
* A `top` into the hosting system shows a growing list of postgres process.
* The processes list decreases once the queries end and if there is no SMS activity client side.

## Consequences
The hardware is consuming more ressources (it's a NAS...)
The maximum DB connections are reached at a moment and internal NAS apps have to wait to access it.
(for this, maybe I could limit concurrent the DB accesses for OC. But it doesn't appear to me as a real fix for it ...)
The system is then being slower !

## Potatoes
Previously. Having noticed these consuming processes, I've tried to kill them all. Bad idea maybe ... Then I've tried to disable OCSMS or OC then reenabling the apps
In order to give DB access to other apps and reduce the consumption.
But they seem to return ... more

Big issue to me.

**Comment by nerzhul** [comment]
Hi @Jef2i thanks for your return. Please tell me if you are doing yourself a delete on those SMS or is this triggered by a syng

**Comment by Jef2i** [comment]
Maybe could I SELECT, or ALTER some non sentitive field but if I don't master a little I don't DELETE neither INSERT anything in it.
So I guess it is coming from an internal function.
`writeToDB` seems to exec this query in some case ...

**Comment by nerzhul** [comment]
@Jef2i what is your max_size for PHP memory options ?

**Comment by Jef2i** [comment]
`phpinfo()` says
`memory_limit => 128M`

**Comment by nerzhul** [comment]
can you increase to 512M ?

**Comment by Jef2i** [comment]
Ok I did it and I still have the same behavior.
As I don't see a higher CPU use I may conclude that prostgres processes have enough memory in usual (ie. non-modified php.ini) case.

**Comment by nerzhul** [comment]
@Jef2i  sory for to be late. what is the delete count ? (if you do a select) ?

**Comment by nerzhul** [comment]
I close the issue as there is a missing index. I added it now to master, will push a new version when more changes will be present
