### ISSUE TITLE
PHP 7 supported?

### ISSUE THREAD

**Issue by enoch85** [nerzhul/ocsms#104]
As the headline says, is PHP 7 supported? If not, please rewrite the code. :)

**Comment by nerzhul** [comment]
@enoch85 very good question, i don't tested it atm, but i'm using owncloud APIs not specific APIs this should work :)

**Comment by nerzhul** [comment]
@enoch85 PHP 7.0.4 is now available in FreeBSD ports, i will upgrade my 5.6 to 7.0.4 if owncloud & wordpress are compatible and answer to your issue

**Comment by enoch85** [comment]
Both Wordpress and ownCloud runs smooth on PHP 7. :)

**Comment by nerzhul** [comment]
@enoch85 i migrated my wordpress & owncloud instance to PHP 7.0.4, everything works great (and my wordpress show pages instanly, before it took ~500ms).
ocsms is compatible with PHP 7
