### ISSUE TITLE
call apps/ocsms/get/new_messages?lastDate=0 at the loading

### ISSUE THREAD

**Issue by Preovaleo** [nerzhul/ocsms#107]
Hi,

When you load the page, i think you start a loop that wait 1s and call apps/ocsms/get/new_messages?lastDate=0.
So when i load the page, i need to wait 1s before see any message.
Yes i know i can wait 1 second, but in my mind each time it happened, i think "broken ?"

Is it possible to load the page before wait ?

### Steps to reproduce
1. load the sms default page
2. nothing happened during one second
3. fisrt new_messages call

### Expected behaviour
don't wait :)

### Actual behaviour
wait :)

### Server configuration

**ownCloud version:** ownCloud 9.0.0 (stable)

**PHP version:** PHP 5.5.9-1ubuntu4.14 (cli)

**HTTPd server:** Apache/2.4.7 (Ubuntu)

**HTTPS:** yes (startcom)

### Client configuration

**Android version:**
5.0.2
**Phone:**
Lg G2 mini
**ownCloud SMS app version:**
last (0.20.1)

### Logs

```
log.swf
```

**Comment by Preovaleo** [comment]
I think it's in the js/public/app.js
i think you need to invert line 403 and 404

**Comment by nerzhul** [comment]
Thanks for your request, it's a trivial fix and i applied it :)
