### ISSUE TITLE
Error	PHP	Undefined variable: r at /var/www/owncloud/apps/ocsms/controller/smscontroller.php#102

### ISSUE THREAD

**Issue by enoch85** [nerzhul/ocsms#109]
### Steps to reproduce
N/A

### Expected behaviour
No error in owncloud.log

### Actual behaviour
``` 
Error	PHP	Undefined variable: r at /var/www/owncloud/apps/ocsms/controller/smscontroller.php#102
``` 
### Server configuration

**ownCloud version:** 
9.0.1
**PHP version:**
PHP 7
**HTTPd server:**
Apache 2.4
**HTTPS:**
Yes
### Client configuration

**Android version:**
6 Marshmallow 
**Phone:**
Nexus 5
**ownCloud SMS app version:**
0.21.2
### Logs

```
Error	PHP	Undefined variable: r at /var/www/owncloud/apps/ocsms/controller/smscontroller.php#102
```

**Comment by nerzhul** [comment]
Thanks for your report, will fix this asap

**Comment by nerzhul** [comment]
Fixed
