### ISSUE TITLE
Duplicate conversations

### ISSUE THREAD

**Issue by azlux** [nerzhul/ocsms#111]
Hi,
Into my ocsms, conversation are duplicated, one with the name (from contacts) and one with the number phone.
Both are updated when I sync my phone.

I don't know how to reproduce that, may be because i've delete/reinstall all contacts into owncloud after installing ocsms.
### Server configuration

**ownCloud version:** 9.0.1

**PHP version:** 7.0.6

**HTTPd server:** nginx + debian8

**HTTPS:** yes (auto-signed)
### Client configuration

**Android version:**0.21.1 ( because the 0.21.2 always make a server don't find error)

**Phone:**Cyanogenmod 12.1

**ownCloud SMS app version:**1.6.4
### Logs

no error into ownclloud.log

**Comment by nerzhul** [comment]
hi @azlux in which country did you reside ? It could be due to an incoherence between your phone and your contacts on owncloud

**Comment by azlux** [comment]
france, you mean because of the +33 into the phone number ? I've checked, and i have duplicated conversation for numbers with and without the country code.

**Comment by nerzhul** [comment]
@azlux i'm french too. On the conversations did you see exactly same phone number in the list when they are opened ?

**Comment by azlux** [comment]
ok, I can see the problem, for duplicate conversations,  06**** numbers appeared into +336**** when the conversation is open

**Comment by nerzhul** [comment]
@azlux seems there is a problem with the dedup algorithm. Have you set your country in the app settings ?

**Comment by azlux** [comment]
Yes, the setting is good, duplicate conversation are more like links, when I click on a 06*** conversation, the +336*** (with the good contact name) appear.

**Comment by azlux** [comment]
ho ! i have a log about ocsms i didn't see because it's appeared only twice this night. I'm not sure it's related
````
{"reqId":"VJUVJnx7BQb+iOBjmQQo","remoteAddr":"37.18.163.7","app":"PHP","message":"call_user_func() expects parameter 1 to be a valid callback, class 'OCA\\OcSms\\Db\\Config' not found at \/*******\/******\/owncloud\/lib\/public\/appframework\/db\/mapper.php#306","level":3,"time":"2016-04-25T09:06:52+00:00","method":"POST","url":"\/index.php\/apps\/ocsms\/set\/country","user":"******"}
````

**Comment by nerzhul** [comment]
i don't think it's related by i take note for a later improvement.

**Comment by azlux** [comment]
into your smscontroler : https://github.com/nerzhul/ocsms/blob/master/controller/smscontroller.php#L90
You check cache number before, so when we enter new phone number, the cache will not be updated.
I'm not sure at all, I didn't take enough time into your code to understand everything.

**Comment by DJaeger** [comment]
The error seems to occur on setting the country setting.
I think it could be, that the country is not set correctly.
Please try to change the country to another one and change back to France.
Than see if there are errors in the log.

**Comment by nerzhul** [comment]
This issue is now fixed
