### ISSUE TITLE
Error after upgrade to Ubuntu 16.04 with PHP 7 and MySQL 5.7

### ISSUE THREAD

**Issue by enoch85** [nerzhul/ocsms#112]
### Steps to reproduce
1. Install Ubuntu 16.04 (forced to use PHP 7 and MySQL 5.7)
2. Get some error about Http (Error # 9)
3. Reinstall the app and wipe database

### Expected behaviour
No errors

### Actual behaviour
```
Exception: {"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing 'INSERT INTO oc_ocsms_smsdatas (user_id, added, lastmodified, sms_flags, sms_date, sms_id,sms_address, sms_msg, sms_mailbox, sms_type) VALUES (?,?,?,?,?,?,?,?,?,?)' with params [\"daniel@en0ch.se\", \"2016-04-27 22:46:36\", \"2016-04-27 22:46:36\", \"11\", \"1460995416638\", 6, \"+46736871223\", \"H\\u00e4rligt\\ud83d\\ude1b\", 0, 1]:\n\nSQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\xF0\\x9F\\x98\\x9B' for column 'sms_msg' at row 1","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php(174): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO oc_...', Array)\n#2 \/var\/www\/owncloud\/lib\/private\/db\/statementwrapper.php(73): Doctrine\\DBAL\\Statement->execute(Array)\n#3 \/var\/www\/owncloud\/apps\/ocsms\/db\/smsmapper.php(297): OC_DB_StatementWrapper->execute(Array)\n#4 \/var\/www\/owncloud\/apps\/ocsms\/controller\/apicontroller.php(103): OCA\\OcSms\\Db\\SmsMapper->writeToDB('daniel@en0ch.se', Array)\n#5 [internal function]: OCA\\OcSms\\Controller\\ApiController->push(1035, Array)\n#6 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#7 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\OcSms\\Controller\\ApiController), 'push')\n#8 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(110): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\OcSms\\Controller\\ApiController), 'push')\n#9 \/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('ApiController', 'push', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#10 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#11 \/var\/www\/owncloud\/lib\/private\/route\/router.php(276): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#12 \/var\/www\/owncloud\/lib\/base.php(882): OC\\Route\\Router->match('\/apps\/ocsms\/pus...')\n#13 \/var\/www\/owncloud\/index.php(39): OC::handleRequest()\n#14 {main}","File":"\/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":115}
```

### Server configuration

**ownCloud version:** 
9.0.1
**PHP version:**
7
**HTTPd server:**
Apache 2.4
**HTTPS:**
Yes
### Client configuration
0.21.2
**Android version:**
6.0.1
**Phone:**
Nexus 5x
**ownCloud SMS app version:**
1.6.4 
### Logs

```
Look --^
```

**Comment by nerzhul** [comment]
Seems you have unicode strange things. Ensure your database is UTF-8. I already have MariaDB 10.1 and PHP 7 and nothing happen. This error is not due to ocsms.

**Comment by KekcuHa** [comment]
Confirm this bug:
owncloud 9.0.2 + php 7
`Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO oc_ocsms_smsdatas (user_id, added, lastmodified, sms_flags, sms_date, sms_id,sms_address, sms_msg, sms_mailbox, sms_type) VALUES (?,?,?,?,?,?,?,?,?,?)' with params ["yavorsky.a", "2016-05-04 08:27:51", "2016-05-04 08:27:51", "11", "1457160513960", 886, "+79857961065", ".\ud83d\ude0a\ud83d\ude0a\ud83d\ude0a\ud83d\ude0a\ud83d\ude0a", 0, 1]: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x98\x8A\xF0\x9F...' for column 'sms_msg' at row 1`

**Comment by nerzhul** [comment]
@KekcuHa what is your database encoding ? utf8 or not ?

**Comment by KekcuHa** [comment]
utf-8:
`CREATE TABLE `oc_ocsms_smsdatas` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`user_id` VARCHAR(64) NOT NULL COLLATE 'utf8_bin',
	`added` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00',
	`lastmodified` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00',
	`sms_id` BIGINT(20) NOT NULL,
	`sms_address` VARCHAR(64) NOT NULL COLLATE 'utf8_bin',
	`sms_msg` VARCHAR(2048) NOT NULL COLLATE 'utf8_bin',
	`sms_date` BIGINT(20) NOT NULL,
	`sms_flags` VARCHAR(2) NOT NULL DEFAULT '00' COLLATE 'utf8_bin',
	`sms_mailbox` SMALLINT(6) NOT NULL,
	`sms_type` SMALLINT(6) NOT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_bin'
ENGINE=InnoDB
AUTO_INCREMENT=1398
;
`

**Comment by nerzhul** [comment]
@KekcuHa thanks, we need to find how to fix this problem if you have ideas, because i'm using standard owncloud API directives for scheme and queries...

**Comment by KekcuHa** [comment]
I've execute this query in mysql client:
`INSERT INTO oc_ocsms_smsdatas (user_id, added, lastmodified, sms_flags, sms_date, sms_id,sms_address, sms_msg, sms_mailbox, sms_type)
VALUES ("yavorsky.a", "2016-05-05 16:22:09", "2016-05-05 16:22:09", "11", "1453562119712", 615, "+79268538617", "\u041f\u0440\u0438\u0432\u0435\u0442! \u0421 \u0434\u043d\u0435\u043c \u0440\u043e\u0436\u0434\u0435\u043d\u044c\u044f! \ud83c\udf89\ud83c\udf89\ud83c\udf89 ", 0, 1);`
and its's executed without error
now let's check what was writed:
 `select sms_msg from oc_ocsms_smsdatas where sms_id=615`
`u041fu0440u0438u0432u0435u0442! u0421 u0434u043du0435u043c u0440u043eu0436u0434u0435u043du044cu044f! ud83cudf89ud83cudf89ud83cudf89`
It's look's like uncorrect encoding somewhere.

**Comment by freeeflyer** [comment]
FYI i just upgraded my trusty to php 7.0 (from ondrej repository) 
I do not experience this error.. if you want me to test something just ask (not destructive, it's a production server)..

**Comment by nerzhul** [comment]
@freeeflyer it seems PHP 5.X is not very compliant with MySQL encoding then...

**Comment by freeeflyer** [comment]
Oh I forgot.. I work with PostgreSQL not MySql
