### ISSUE TITLE
JSON data corrupted ?

### ISSUE THREAD

**Issue by JujuBickoille** [nerzhul/ocsms#113]
Hello,

I've a trouble with app on my NGINX's configuration, I dunno what to do, maybe you got some ideas...

When I go to the app tab, I got many know contact displays with their phone number and they are set as unread ( same in issue #95 ).

When I read my ngnix's log, I got some really crazy things inside:

`2016/04/30 20:58:30 [info] 8333#0: *5555 client sent too long header name or value: "/9j/4AAQSkZJRgABAQAAAQABAAD//gA+Q1JFQVRP`**REALLY LONG BASE64 STRING**`..." while processing SPDY, client: 192.168.6.1, server: localhost`

When I look in the ' network ' tab of developper tool of firefox, both /index.php/apps/ocsms/get/peerlist and /index.php/apps/ocsms/get/new_messages?lastDate=0 are corrupt:

When I call both JSON from other tab, directly ( without use app ) they are both okay. I've try to curl them, same, both are okay...
If I undestand well, that like if a part of of the JSON data was interpreted by a new request oO the base64 string, and of course is really huge for nginx... but... why ?!

Onwncloud logs don't say me anything, just nginx. that's logic I think if my idea is good. I didn't say that, but sync is okay with phones
### Server configuration

**ownCloud version:** 
9.0.1 ( same with 9.0.0 )

**PHP version:**
PHP 5.6.20-pl0-gentoo

**HTTPd server:**
nginx version: nginx/1.8.1
built with OpenSSL 1.0.2f  28 Jan 2016 (running with OpenSSL 1.0.2g  1 Mar 2016)
TLS SNI support enabled
configure arguments: --prefix=/usr --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error_log --pid-path=/run/nginx.pid --lock-path=/run/lock/nginx.lock --with-cc-opt=-I/usr/include --with-ld-opt=-L/usr/lib64 --http-log-path=/var/log/nginx/access_log --http-client-body-temp-path=/var/lib/nginx/tmp/client --http-proxy-temp-path=/var/lib/nginx/tmp/proxy --http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi --http-scgi-temp-path=/var/lib/nginx/tmp/scgi --http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi --with-pcre --with-http_dav_module --with-http_mp4_module --with-http_spdy_module --with-http_stub_status_module --with-http_realip_module --add-module=external_module/nginx-upload-progress-module-0.9.1 --add-module=external_module/headers-more-nginx-module-0.26 --add-module=external_module/ngx_cache_purge-2.3 --add-module=external_module/nginx-dav-ext-module-0.0.3 --with-http_ssl_module --without-mail_imap_module --without-mail_pop3_module --without-mail_smtp_module --user=nginx --group=nginx

**HTTPS:**
Only HTTPS ( 80:tcp closed and nftables DROP )
### Client configuration

**ownCloud SMS app version:**
git checkout v1.6.4

Thank you :Ð

**Comment by nerzhul** [comment]
Hello
this base 64 string is your contact photo as viewed in contact app. Did it work on contact app ?

**Comment by JujuBickoille** [comment]
Hello nerzhul,

Yeah I don't have problem with the contact app, all contact photos are correctly show in contact App.

**Comment by JujuBickoille** [comment]
the contact app is using base64 image, I can see they provides from /remote.php/dav/addressbooks/users/<username>/contacts/

I see the XML with image encoded in base64

You think it can be possible error provide from an invalid photo ?

**Comment by JujuBickoille** [comment]
I've try many things and I found some good things.

1st, I've cleanup my contacts, I've change all phone numbers to same syntax ( +<countrycode><phonenumber> )
=> example: before => "01 11 33 74 17" after => "+33111337417"
2) I've change all entry in database to match exact new phone number
UPDATE oc_ocsms_smsdatas  SET sms_address = REPLACE(sms_address, '01 11 33 74 17', '+33111337417') WHERE sms_address='01 11 33 74 17';
3) When I've done, it was really less ugly ( but same troubles with nginx )
4) I've try to truncate oc_ocsms_user_datas as described in #95 
=> same result...
5) I've try to play with code, I've try to change the lastDate=0 to the current date, I've set it to 1462102497970 for a test ( in app.js on g_lastMsgDate ), and now I don't have nginx troubles, and no duplicates contact list !

it can solve it if we change the g_lastMsgDate with the current timestamp ?

**Comment by JujuBickoille** [comment]
Finally, when I receive a new message it is still wrong, I got the error in nginx :|

It comes when I have an unreaded message, it make a duplicate contact with the 1st with unread message and 2nd contact with photo and " no new message " status

Thank you

**Comment by nerzhul** [comment]
hi @JujuBickoille we change some things in the API in 1.7.0, does the issue affect yourself with last version ?

**Comment by JujuBickoille** [comment]
Hello @nerzhul 
I've install the 1.7.0 and it's same. I got same troubles:

=> All messages are set unread when I switch app and come again
=> all user pictures are broke

[https://cloud.famille-perret.ovh/ocsms.png](url)

The good things is I have no error in my logs and JSONs don't seem to be corrupt so it's better :Ð

**Comment by JujuBickoille** [comment]
Maybe the same than #117  I'm using now owncloud v9.1.0

**Comment by nerzhul** [comment]
@JujuBickoille i need to do some IHM fix but lack some time, if you know angular JS maybe you can help me :)

**Comment by nerzhul** [comment]
Pictures are now fixed, can you confirm ?

**Comment by JujuBickoille** [comment]
Yes, it work perfectly now !

Thank you very much =)

**Comment by nerzhul** [comment]
Closing as it's fixed but i forget the feedback :)
