### ISSUE TITLE
add support for silence

### ISSUE THREAD

**Issue by tchncs** [nerzhul/ocsms#115]
hi there,

i prefer to use the app [Silence](https://github.com/SilenceIM/Silence) for my sms.
is it possible to support it also? :)

regards!

**Comment by Dragnucs** [comment]
Yes, supportting Silence would be great.

**Comment by nerzhul** [comment]
hi, can you backport this change to nerzhul/owncloud-SMS-App please ? this is not related to server side

**Comment by Dragnucs** [comment]
Here you go: https://github.com/nerzhul/ownCloud-SMS-App/issues/107

**Comment by nerzhul** [comment]
Thanks
