### ISSUE TITLE
Picture of contacts not displayed

### ISSUE THREAD

**Issue by FrederikLauber** [nerzhul/ocsms#116]
Hi,

I noticed that my contacts do not have there picture properly displayed anymore.
See Screenshot for more information.
![unbenannt](https://cloud.githubusercontent.com/assets/17728264/17789612/3f38e10c-6593-11e6-87f8-5f01bfc3f2f4.png)

Version is 1.7.0

### Steps to reproduce
1. Have a conversation with a contact with a picture
2.
3.

### Expected behaviour
The contact should display the picture

### Actual behaviour
A "image broken" symbol is displayed. If one selects to display the image, the message "The image ... cannot be displayed as it contains errors"

### Server configuration

**ownCloud version: 9.0.4** 

**PHP version: 7.0.5**

**HTTPd server: Apache 2.2  **

**HTTPS: yes**

### Client configuration

Firefox 47.0.1

**Comment by nerzhul** [comment]
Hi, can you give me an example URL for your contact images, looking at the source page code ?

Thanks

**Comment by FrederikLauber** [comment]
Hi,

you mean this: 
data:image/png;base64,aHR0cHM6Ly9jbG91ZC5mbGFtYmRhLmRlL3JlbW90ZS5waHAvZGF2L2FkZHJlc3Nib29rcy91c2Vycy9wOTEva29udGFrdGUvQzcyRjcyMzYtNEQ2MC0wMDAxLTI0NzAtMUUwMDFDODAxNDFFLnZjZj9waG90bw==

?
Or something else?

**Comment by nerzhul** [comment]
Hi @FrederikLauber i think it's a contact app issue somewhere. I noticed the same problem for me when i upgraded to nextcloud 10.0. I will look at this this weekend

**Comment by nerzhul** [comment]
This is now fixed
