### ISSUE TITLE
conversations get duplicated

### ISSUE THREAD

**Issue by binome333** [nerzhul/ocsms#117]
Since my upgrade to owncloud 9.1.0, when I open a conversation and wait for a time (not doing anything), the whole conversation gets printed (duplicated) again and again, every 10sec.
eg.
T=0:
"Hi there
Jul 9, 2016 1:22:46 PM"
                                     "I'm here
                                      Jul 9, 2016 1:25:00 PM"

T=10sec:
"Hi there
Jul 9, 2016 1:22:46 PM"
                                     "I'm here
                                      Jul 9, 2016 1:25:00 PM"
"Hi there
Jul 9, 2016 1:22:46 PM"
                                     "I'm here
                                      Jul 9, 2016 1:25:00 PM"

T=20sec:
"Hi there
Jul 9, 2016 1:22:46 PM"
                                     "I'm here
                                      Jul 9, 2016 1:25:00 PM"
"Hi there
Jul 9, 2016 1:22:46 PM"
                                     "I'm here
                                      Jul 9, 2016 1:25:00 PM"
"Hi there
Jul 9, 2016 1:22:46 PM"
                                     "I'm here
                                      Jul 9, 2016 1:25:00 PM"

and so on
### Server configuration

**ownCloud version:** 
9.1.0

**PHP version:**
5.6.25

**HTTPd server:**
Apache 2.2.2 (Debian)
### Client configuration

**Android version:**
6.0.1

**Phone:**
Galaxy S7

**ownCloud SMS app version:**
0.21.2

**Comment by nerzhul** [comment]
Thanks for your report, i will look at this shortly

**Comment by pawlosck** [comment]
The same problem on nextcloud 10.0.1. Upgrade from owncloud 9.0.3 if I remember well. On OwnCloud I couldn't display anything. I saw animated lines only.
In my case, probably last downloaded sms are duplicated only.  When I refresh website, duplicated sms are removed from screen but after few seconds sms are duplicated again every few seconds.
Sms stored to database are not duplicated/removed from database. Sms are duplicated on screen only.

Server configuration
NextCloud version:
10.0.1

PHP version:
5.6.27

HTTPd server:
Apache/2.4.10 (Debian)

Client configuration
Android version:
4.4.2

ownCloud SMS app version:
0.21.2

**Comment by DJaeger** [comment]
For me it looks a little different:

T=0:
"Hi there
Jul 9, 2016 1:22:46 PM"
"I'm here
Jul 9, 2016 1:25:00 PM"

T=10sec:
"Hi there
Jul 9, 2016 1:22:46 PM"
"Hi there
Jul 9, 2016 1:22:46 PM"
"I'm here
Jul 9, 2016 1:25:00 PM"
"I'm here
Jul 9, 2016 1:25:00 PM"

T=20sec:
"Hi there
Jul 9, 2016 1:22:46 PM"
"Hi there
Jul 9, 2016 1:22:46 PM"
"Hi there
Jul 9, 2016 1:22:46 PM"
"I'm here
Jul 9, 2016 1:25:00 PM"
"I'm here
Jul 9, 2016 1:25:00 PM"
"I'm here
Jul 9, 2016 1:25:00 PM"

and so on

### Server configuration

**ownCloud version:**
8.2.7

**PHP version:**
5.6.12

**HTTPd server:**
Apache/2.4.20
### Client configuration

**Android version:**
6.0.1

**Phone:**
Galaxy S4

**ownCloud SMS app version:**
0.22.2

**Comment by nerzhul** [comment]
I think the problem is message fetching, we didn't instruct server with correct informations on the first refresh. Then the message is dup. If i remember messages are an array, maybe we should have a dict with message_time as key (as it's in microsec)

**Comment by DJaeger** [comment]
For me it looks a little different:

T=0:
"Hi there
Jul 9, 2016 1:22:46 PM"
"I'm here
Jul 9, 2016 1:25:00 PM"

T=10sec:
"Hi there
Jul 9, 2016 1:22:46 PM"
"Hi there
Jul 9, 2016 1:22:46 PM"
"I'm here
Jul 9, 2016 1:25:00 PM"
"I'm here
Jul 9, 2016 1:25:00 PM"

T=20sec:
"Hi there
Jul 9, 2016 1:22:46 PM"
"Hi there
Jul 9, 2016 1:22:46 PM"
"Hi there
Jul 9, 2016 1:22:46 PM"
"I'm here
Jul 9, 2016 1:25:00 PM"
"I'm here
Jul 9, 2016 1:25:00 PM"
"I'm here
Jul 9, 2016 1:25:00 PM"

and so on

### Server configuration

**ownCloud version:**
8.2.7

**PHP version:**
5.6.12

**HTTPd server:**
Apache/2.4.20
### Client configuration

**Android version:**
6.0.1

**Phone:**
Galaxy S4

**ownCloud SMS app version:**
0.22.2

**Comment by DJaeger** [comment]
The network analysing of the Firefox Developer Tools is showing me, that these request are done every few seconds.
https://cloud.example.com/index.php/apps/ocsms/get/new_messages?lastDate=1478457957328
https://cloud.example.com/index.php/apps/ocsms/get/conversation?phoneNumber=%2B4917XXXXXXXX&lastDate=1478457957328

It seems, that the response of "conversation" is completely added to the current array of messages.
Not only new messages.

**Comment by nerzhul** [comment]
thanks for the return back for this behaviour, will look at this except if someone is faster than me to provide a patch :)
