### ISSUE TITLE
NextCloud

### ISSUE THREAD

**Issue by animalillo** [nerzhul/ocsms#118]
I was wondering if you are planning to give support for nextcloud as I've been thinking in migrating my oc instance to nexcloud and I like this app a lot, and a lot of apps are migrating to nextcloud

**Comment by nerzhul** [comment]
This is already the case as i'm developping on it
App is on the store

https://apps.nextcloud.com/app/ocsms

**Comment by animalillo** [comment]
link gives page not found, but it's good to know!
