### ISSUE TITLE
OwnCloud SMS cause problem with calendar/contacts/tasks/files synchronisation

### ISSUE THREAD

**Issue by pawlosck** [nerzhul/ocsms#120]
When I installed owncloud sms app on NextCloud, I lost possibility to synchronisation calendar/contacts/tasks (DAVDroid) and files synchronisation (NextCloud app for Android).
When I try to synchro files, I see message about failed operation. The same problem during calendar/contacts/tasks synchronisation. DAVDroid can synchronise, but very rarely. One every 30-40 attempts.

I have problems to login and logout when sms app is enabled. I have to restart apache to login to nextcloud.
Logs display this message
{"reqId":"XXXXXXX","remoteAddr":"127.0.0.1","app":"remote","message":"An exception occurred while executing 'UPDATE \"oc_authtoken\" SET \"last_check\" = ? WHERE \"id\" = ?' with params [NUMBER, NUMBER]:\n\nSQLSTATE[HY000]: General error: 5 database is locked","level":4,"time":"2016-10-27T17:00:19+00:00","method":"GET","url":"\/nextcloud\/status.php","user":"pawel"}

When I disabled sms app on NextCloud, synchronisation started work.

Server configuration
NextCloud version:
10.0.1

PHP version:
5.6.27

HTTPd server:
Apache/2.4.10 (Debian)

Client configuration
Android version:
4.4.2

ownCloud SMS app version:
0.21.2

**Comment by nerzhul** [comment]
This is a very very strange issue. The request you show is not related to ocsms. Are you using sqlite ? If yes i think this is an issue with concurrent access to your sqlite database. ocsms calls its own tables (not others, except the sessions, but using the nextcloud API) when syncing.
I think you should switch to pgsql or mysql.

**Comment by pawlosck** [comment]
Bug fixed when I cloned today repo. Probably bug connected with duplicated messages.


commit 8ecf36046259f2af2e30a46b03fcdaf0bab41361
Date:   Fri Nov 11 17:14:46 2016 +0100
Fix conversation loader shown where no conversation choosen

**Comment by nerzhul** [comment]
perfect then :)
