### ISSUE TITLE
Screenshots missing from Nextcloud appstore entry

### ISSUE THREAD

**Issue by olantrust** [nerzhul/ocsms#124]
Currently there is no image present for the entry for this app, which doesn't look great, and an image (or better images) would help appstore users get a feel for what the app is.

**Comment by nerzhul** [comment]
@olantrust i saw this issue when publishing it. I haven't got time to fix this issue yet

**Comment by jancborchardt** [comment]
@nerzhul also, it’s still called »ownCloud SMS« there which is a bit confusing. ;)

**Comment by nerzhul** [comment]
@jancborchardt in fact the main problem was the app done for owncloud before the fork, just calling it sms is hard, maybe should i call it "phone" because i think about adding more phone sync features...

**Comment by nerzhul** [comment]
if someone has time to provide a PR with nice screenshots + app config, don't hesitate

**Comment by enoch85** [comment]
@nerzhul What about "Phone Sync"?

**Comment by nerzhul** [comment]
@enoch85 sync call log for example, maybe other features, there are many possibilities but it only need time and hands

**Comment by enoch85** [comment]
@nerzhul I meant the name of the app ;)

**Comment by nerzhul** [comment]
@enoch85 oh sorry, i misunderstood, in fact i can rename the label to a similar thing, but please note i cannot rename easily the technical name, it's same thing on playstore because the appname is unique over all the playstore :)
Phone Sync seems reasonable, yes, i will think about it and how to migrate labels to this name, the only problem remain android itself where the name is too generic but if owncloud is dying maybe i should rename to NextCloud Phone Sync

**Comment by enoch85** [comment]
@nerzhul Thanks!

Why not just "Phone Sync" to fit all needs in the future as well...? Anyway, thanks again for your efforts.

**Comment by nerzhul** [comment]
for the NextCloud Phone Sync it's for Android only, not nextcloud app, which knows it runs on nextcloud :)

**Comment by jancborchardt** [comment]
@nerzhul only one thing, remember it’s capitalized »Nextcloud« with small c ;)
You could call it »Phone sync for Nextcloud« or »SMS sync for Nextcloud«. Then the important stuff comes first.

**Comment by nerzhul** [comment]
This but is now fixed, thanks for the report. I will open an issue to rename application comments will be welcome.

Here is the issue: https://github.com/nerzhul/ocsms/issues/132
