### ISSUE TITLE
Incompatible with Nextcloud 11

### ISSUE THREAD

**Issue by CountMurphy** [nerzhul/ocsms#128]
### Steps to reproduce
1.Upgrade to Nextcloud 11

Running ownCloud SMS 1.11.0. Error message:

- This app has no maximum Nextcloud version assigned. This will be an error in the future.
- This app cannot be installed because the following dependencies are not fulfilled:
   Server version **9.2 or lower is required.**

**Comment by CountMurphy** [comment]
Looks like you fixed it. Thansk!

**Comment by nerzhul** [comment]
Yes it's fixed before release :) you just need to upgrade
