### ISSUE TITLE
Use loading spinner from core

### ISSUE THREAD

**Issue by stefan-niedermann** [nerzhul/ocsms#130]
To get a consisten look and feel in Nextcloud you should use the default spinner instead of the current.
A span with class `icon-loading` shows the core spinner.

**Comment by nerzhul** [comment]
@stefan-niedermann why not, can you provide a PR with before & after screenshot to show the difference ?

**Comment by stefan-niedermann** [comment]
> @stefan-niedermann why not, can you provide a PR with before & after screenshot to show the difference ?

Sure, it's not much work, i can do even more: Here's a PR that switches to core spinner (has to be reviewed and tested) #133

**Comment by nerzhul** [comment]
Okay for me, the change is trivial
