### ISSUE TITLE
Renaming application

### ISSUE THREAD

**Issue by nerzhul** [nerzhul/ocsms#132]
As you know Nextcloud is growing more and more.

ownCloud SMS application name using Nextcloud seems an aberation.
As i want add more features than only receiving SMS from phones (maybe GPS position + call logs, adding an API for other app to fetch those data to do nice things in owncloud), i think we should have a better name.

Please add your propositions or comments.

Here are some current propositions:
* Phone
* Phone sync

**Comment by nerzhul** [comment]
I also link the following issue for client side, as this is a very interesting work:

https://github.com/nerzhul/ownCloud-SMS-App/pull/118

**Comment by enoch85** [comment]
A few more:
- NextPhone Sync
- NSync Phone
- Next Phone

**Comment by stefan-niedermann** [comment]
Hm. I think we should pay attention for the following points:
- "Nextcloud" should be used - has a more official character and most of the other well-known apps do it, too.
- The name should be as short as possible - But i would be fine with "Nextcloud Phone Sync" - and when there is not much space, e. g. in the Nextcloud app menu or the android-launcher just name it "Phone Sync" - this is the way Notes does it: It is called "Nextcloud Notes" but when there is no much space it shows only the generic "Notes".

So i vote for "**Nextcloud Phone Sync**" as official name and "Phone Sync" if there is not enough space.

**Comment by enoch85** [comment]
Would be nice with more input on this, anyone else with a sugesstion, or should we go for `(Nextcloud) Phone Sync`

**Comment by jancborchardt** [comment]
»Phone sync for Nextcloud« seems to be even better. That puts the important parts first and makes them visible.

Please no strange names with weird capitalization like »NextPhone« or so. ;) People need to understand from the name what it does. :)

**Comment by olantrust** [comment]
Nextcloud Phonesync
No need for 'phone sync' - easier and looks less cluttered just to have phonesync.
That way around also obviates the need for the word 'for' which looks clumsy.

**Comment by nerzhul** [comment]
@jancborchardt thanks for inviting me in nextcloud organization, what can i do ? do you want me to fork the application in nextcloud group and maintain it in the group ?

**Comment by enoch85** [comment]
I think NSync is the best option actually... https://www.youtube.com/watch?v=GQMlWwIXg3M&feature=youtu.be&t=42s

**Comment by stefan-niedermann** [comment]
> »Phone sync for Nextcloud« seems to be even better. That puts the important parts first and makes them visible.

Strange. So why are the other applications not called "Notes for Nextcloud", "News for Nextcloud", "Files for Nextcloud" and "Mail for Nextcloud"...? Does not seem to be very consistent to be honest...

**Comment by skjnldsv** [comment]
PhoneSync seems good to me. I wouldn't bother adding for nextcloud or else like @stefan-niedermann said.

**Comment by nerzhul** [comment]
okay, Phone Sync then

**Comment by stefan-niedermann** [comment]
@nerzhul if this is the final decision i will provide pull requests for the README.md-files (client & server) and for a [new icon](https://github.com/nerzhul/ownCloud-SMS-App/pull/118#issuecomment-267283056) (client & server).

**Comment by stefan-niedermann** [comment]
May i suggest to rename the repositorys?
nextcloud-phone-sync (ocsms)
nextcloud-phone-sync-android (ownCloud-SMS-App)

**Comment by nerzhul** [comment]
@stefan-niedermann renaming the repository will break F-Droid build, somebody should fix it, and for repository names, it should be done yes, but a nextcloud dev invite me in nextcloud organization i think it can be useful to migrate server side to it

**Comment by stefan-niedermann** [comment]
> but a nextcloud dev invite me in nextcloud organization i think it can be useful to migrate server side to it

Totally agree :)

> renaming the repository will break F-Droid build, somebody should fix it

Totally disagree 😆 i renamed https://github.com/stefan-niedermann/nextcloud-notes recently and github creates automatically redirections, so the old links will still work without problems. F-Droid has no problem with this (nextcloud-notes is at F-Droid, too). The **only** thing that is really important is to keep the package-id the same.

But you are right, if the repo moves to github.com/nextcloud a renaming would make no sense.
