### ISSUE TITLE
Style messages more modern

### ISSUE THREAD

**Issue by stefan-niedermann** [nerzhul/ocsms#134]
Imho the rounded bubbles look quiet old school (though they are functional :) )
I'd like to suggest a new look & feel for the chat entries.
- Lighter backgrounds should increase contrast and readability
- No border-radius (at least not this much) to look more modern

But since design is personal taste, you @nerzhul have to deside whether or not i will create a PR.
And since one image tells more than a thousand words:

**old:**

![bildschirmfoto vom 2016-12-15 12 43 15](https://cloud.githubusercontent.com/assets/4741199/21222877/7b1dea94-c2c4-11e6-9c4f-4f9a31a0b9ba.png)

**new:**

![bildschirmfoto vom 2016-12-15 12 40 23](https://cloud.githubusercontent.com/assets/4741199/21222880/7eb82516-c2c4-11e6-8553-b9f46ffa3e52.png)

**Comment by enoch85** [comment]
@stefan-niedermann You rock! :rocket:

**Comment by nerzhul** [comment]
Very nice work !

**Comment by nerzhul** [comment]
I like it, just the header design is ugly now :)

**Comment by stefan-niedermann** [comment]
Always do small steps to get to the goal :)

**Comment by nerzhul** [comment]
Merged, thanks
