### ISSUE TITLE
Can't activate on Nextcloud 11,  64bit or higher PHP required.

### ISSUE THREAD

**Issue by JSoko** [nerzhul/ocsms#139]
### Steps to reproduce
1. Update to Nextcloud 11.0
2. try to activate app
3. can't activate,  64bit or higher PHP required.

### Expected behaviour
Shold be possible to activate also on systems jast with PHP 7 32 bit (Armhf; odroid )

### Actual behaviour
 can't activate,  64bit or higher PHP required.

### Server configuration
**Operating system**: Linux OdOc 3.10.96 #1 SMP PREEMPT Mon May 23 01:50:06 BRT 2016 armv7l

**Web server:**  apache2handler

**Database:** mysql

**PHP version:** 7.0.8-0ubuntu0.16.04.3

**Nextcloud version:** 11.0.0.10

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** 

**Signing status:**
<details>
	<summary>Signing status</summary>

	```
	Array	```
</details>

**List of activated apps:**
<details>
	<summary>App list</summary>

	```
	Enabled:
	 - activity: 2.4.1
	 - admin_audit: 1.1.0
	 - bookmarks: 0.9.1
	 - calendar: 1.4.1
	 - comments: 1.1.0
	 - contacts: 1.5.2
	 - dav: 1.1.1
	 - direct_menu: 0.9.3
	 - federatedfilesharing: 1.1.1
	 - files: 1.6.1
	 - files_automatedtagging: 1.1.1
	 - files_pdfviewer: 1.0.1
	 - files_sharing: 1.1.1
	 - files_texteditor: 2.2
	 - files_trashbin: 1.1.0
	 - files_versions: 1.4.0
	 - files_videoplayer: 1.0.0
	 - html5_videoplayer: 1.0
	 - issuetemplate: 0.0.1
	 - keeweb: 0.3.0
	 - logreader: 2.0.0
	 - lookup_server_connector: 1.0.0
	 - news: 10.1.0
	 - nextcloud_announcements: 1.0
	 - nextnotes: 0.9.1
	 - notifications: 1.0.1
	 - password_policy: 1.1.0
	 - provisioning_api: 1.1.0
	 - serverinfo: 1.1.1
	 - sharebymail: 1.0.1
	 - spreedme: 0.3.5
	 - survey_client: 0.1.5
	 - systemtags: 1.1.3
	 - tasks: 0.9.4
	 - templateeditor: 0.2
	 - theming: 1.1.1
	 - twofactor_backupcodes: 1.0.0
	 - updatenotification: 1.1.1
	 - workflowengine: 1.1.1

	Disabled:
	 - encryption
	 - external
	 - federation
	 - files_accesscontrol
	 - files_external
	 - files_retention
	 - firstrunwizard
	 - flowupload
	 - gallery
	 - ocsms
	 - ownbackup
	 - qownnotesapi
	 - shorten
	 - user_external
	 - user_ldap
	 - user_saml
	```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "default_language": "de_DE",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "\/var\/www\/owncloud\/data",
    "tempdirectory": "\/media\/ssd\/phptemp\/",
    "dbtype": "mysql",
    "version": "11.0.0.10",
    "theme": "",
    "maintenance": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "integrity.check.disabled": false,
    "dbname": "owncloud",
    "dbhost": "127.0.0.1",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "loglevel": 2,
    "logtimezone": "Europe\/Berlin",
    "log_rotate_size": 500000,
    "cron_log": true,
    "asset-pipeline.enabled": false,
    "assetdirectory": "\/var\/www\/owncloud",
    "maxZipInputSize": 2147483648,
    "overwritewebroot": "\/",
    "overwrite.cli.url": "\/",
    "htaccess.RewriteBase": "\/",
    "allowZipDownload": true,
    "versions": "true",
    "versions_retention_obligation": "1,3",
    "instanceid": "5072f7e9eec7e",
    "knowledgebaseenabled": true,
    "check_for_working_webdav": true,
    "check_for_working_htaccess": true,
    "check_for_working_wellknown_setup": true,
    "has_internet_connection": true,
    "forcessl": true,
    "activity_expire_days": 8,
    "appcodechecker": true,
    "skeletondirectory": "",
    "trashbin_retention_obligation": "auto,15",
    "appstore.experimental.enabled": true,
    "trusted_domains": [
        "XXX.net",
        "xxx.net",
        "192.168.1.234"
    ],
    "mail_smtpmode": "smtp",
    "mail_smtphost": "smtp.1und1.de",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "no-reply",
    "mail_domain": "of99.de",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "updater.release.channel": "stable",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

**Comment by nerzhul** [comment]
Sorry but we didn't use any 64bit pure feature, only dates are 64 bits integer, but PHP should handle it properly, we only use PHP integers

**Comment by nerzhul** [comment]
Err, i see we talk about 64 integer in our dependencies, it's due to Android dates... hmmm, can you test a thing for me ?

in appinfo/info.xml, remove this line:

<php min-version="5.6" min-int-size="64"/>

Next, sync your SMS and tell me if you have the correct date in server app.

Thanks

**Comment by JSoko** [comment]
> can you test a thing for me ?
of course...
> in appinfo/info.xml, remove this line:
which line?
> Next, sync your SMS and tell me if you have the correct date in server app.

**Comment by JSoko** [comment]
I've now changed
` <php min-version="5.6" min-int-size="64"/>`
to
` <php min-version="5.6" min-int-size="32"/>`
in info.xml and could activate the app.

Now synced with my handy...
Dates are shown corrct with amican notation.

:-)

**Comment by nerzhul** [comment]
Okay, then i add this fix to code, thanks for the review
