### ISSUE TITLE
Can't install on 32bit server

### ISSUE THREAD

**Issue by elvirolo** [nerzhul/ocsms#141]
I'm trying the install ocsms 1.11.3 on an Nextcloud 11 instance running on an ARMv7 (32-bit) board.

### Steps to reproduce
1. Go to the Nextcloud app store or download ocsms manually.

### Expected behaviour
One should be able to click on the "enable" button.

### Actual behaviour
The following error is displayed: 
"This app cannot be installed because the following dependencies are not fulfilled:
64bit or higher PHP required."

### Server configuration
**Machine:** Armbian (Debian) Jessie on an Olimex Olinuxino Lime2 board.

**ownCloud version:** 11

**PHP version:** 5.6.29-0

**HTTPd server:** Apache 2.4.10

**HTTPS:** enabled

### Client configuration

**Android version:** -

**Phone:** -

**ownCloud SMS app version:**  1.11.3

**Comment by enoch85** [comment]
https://github.com/nerzhul/ocsms/issues/139#issuecomment-267944715

**Comment by elvirolo** [comment]
Sorry, I should have checked closed issues - I missed that one! Thank you very much.

**Comment by nerzhul** [comment]
no problem @elvirolo
