### ISSUE TITLE
64bit or higher PHP required

### ISSUE THREAD

**Issue by simonspa** [nerzhul/ocsms#142]
I cannot install your app on Nextcloud 11 running on a Raspberry Pi.

### Steps to reproduce
1. Goto App store in Nextcloud 11
2. Check the Nextcloud SMS app

### Expected behaviour
"Enable" button active, allowing installation

### Actual behaviour
Error message shown:

> This app cannot be installed because the following dependencies are not fulfilled:
    64bit or higher PHP required.

### Server configuration

**Nextcloud version:**  11.0

**PHP version:** 5.6.27

**HTTPd server:** nginx

**HTTPS:** forced

Platform: Raspberry Pi 2 B, running Raspbian Jessie (32bit)

**Comment by nerzhul** [comment]
Already fixed.
