### ISSUE TITLE
Account configured on NextCloud app on Android not visible in application

### ISSUE THREAD

**Issue by fir3wall** [nerzhul/ocsms#143]
### Steps to reproduce
1. Install NextCloud app (1.4.0)
1.1. Configure your account in application 
2. Install onwCloud-SMS app version 0.23.2

### Expected behaviour
Account configured in NextCloud application is not visible on My Accounts list. 

### Actual behaviour
Account configured in NextCloud application is not visible on My Accounts list. Tried to remove account from system settings -> accounts and then add it again using SMS app but still it's not visible. 

### Server configuration
**NextCloud version:** 
11 (last stable)

### Client configuration
**Android version:**
6.0.1
**Phone:** 
Galaxy S7 Edge

**Comment by nerzhul** [comment]
Hmmm strange, when testing on android emulator i saw the account. Maybe it's due to recent code refactoring to remove owncloud library and doing REST call ourselves. Will investigate soon.
Did you see the account in the app account list ?

**Comment by nerzhul** [comment]
Oh i see the problem, in fact you think you can use the Nextcloud account to use owncloud SMS app, sorry but it's not possible at this moment because there is no sync between Nextcloud app & OcSMS app for name & sync parameters, and i think it's not very simple to do without breaking all clients.
Please add a Owncloud SMS account instead

**Comment by fir3wall** [comment]
Yeah that what I was thinking is an issue - OK so I've downloaded your app from NextCloud store and what I need now on my phone - ownCloud app instead of NextCloud ? Tried to add this does not work for some reason. 

Sorry little bit lost now!
D

**Comment by nerzhul** [comment]
no, you need to download Owncloud SMS from play store or F-Droid (second is unofficial), links are in the app repository https://github.com/nerzhul/ownCloud-SMS-App

**Comment by fir3wall** [comment]
Hello, This is app that I have downloaded in most recent version and I still cannot see on the list my NextCloud account.
