### ISSUE TITLE
Sync SMS messages from Signal

### ISSUE THREAD

**Issue by Bugsbane** [nerzhul/ocsms#145]
Hi there,

This app looks like exactly what I need, however, given that I - like many Nextcloud users - am privacy conscious I use Signal as a more secure and privacy conscious option than the standard SMS app.

I'm wondering if it would be possible to extend this app to also import from Signal, even if it required a regular manual export from Signal (which already has an option to export all messages).

The Nextcloud Android app is supposedly getting the ability to sync different file types from manually selected folders, so it could even regularly sync exported messages, however it would be great to have this app to actually parse and show those messages in a more integrated manner.

**Comment by nerzhul** [comment]
It's a client side issue and it's already asked in the client app repository
