### ISSUE TITLE
FTP download link changed

### ISSUE THREAD

**Issue by di72nn** [nerzhul/ocsms#147]
ownCloud's internal updater tries to download https://ftp.unix-experience.fr/owncloud-sms/v1.11.4.zip, while the actual file is uploaded without "v" in it's name (https://ftp.unix-experience.fr/owncloud-sms/1.11.4.zip). This obviously results in `404 Not Found`.

"Download" button on this page fails too: https://apps.owncloud.com/content/show.php/ownCloud+SMS?content=167289.

Sorry if this is not the right place to report it.

**Comment by nerzhul** [comment]
exact, thanks for the report on owncloud app store, i fixed it now
