### ISSUE TITLE
Reuse colors from the contact app

### ISSUE THREAD

**Issue by stefan-niedermann** [nerzhul/ocsms#149]
# Current behavior

ocsms seems to generate new colors for each conversation which may be different from the ones used in contacts app

# Expected behavior

ocsms should check if the contact exists in the contacts app and reuse the color from there

**When** there is a contact in the contacts app that matches the entry in ocsms
**Then** the color from the contacts app should be used

**When** there is no contact that can be associated
**Then** you can define your own color *or* use a static grey color (because it could simplify your code if you don't need color generators at all - assuming most people who use ocsms will host their contacts at nextcloud, too)

# Benefit

1. Less confusion because the user can assign **one** color to **one** contact (1:1 relation)
2. Better colors - sorry, but contacts app is simply doing it better (nicer colors, better contrast, better readability)

**Comment by nerzhul** [comment]
In fact i was using same color generation than contact app but maybe it has evolved and i didn't follow it

**Comment by skjnldsv** [comment]
No no, it's fine!
It depends on what string you're using to generate the colours. You're use of `str.toHsl()` is very good, but instead of using `contact.label | peerColor`, you should use the contact uid `contact.uid() | contactColor`

**Comment by nerzhul** [comment]
contact object is not a contact app object, but a ocsms contact object, it's a little bit different because it's a simpler object not linked with database, as all phone numbers aren't known by contact app
