### ISSUE TITLE
Add support for US number format

### ISSUE THREAD

**Issue by mozzwald** [nerzhul/ocsms#15]
I am having same issue as https://github.com/nerzhul/ocsms/issues/13 but with US formatted phone numbers.

It is common in US to format numbers with parentheses and hyphen like (XXX) XXX-XXXX. This causes split listings in OCSMS, one matched to the contact (sender, with US format number) and the other listed as the 10 digit number with no formating (XXXXXXXXXX). This problem can be fixed by adding the phone number to contact without US formatting but it would be nice for the app to do this for you.

**Comment by nerzhul** [comment]
Work in progress.

Added a basic countrycode mapper based on Google Play Store buyers stats (ocsms and global stats): https://github.com/nerzhul/ocsms/commit/ab3bd8718eba817bba14c6bddc8fef3ea9374bbc

If you want your country in the mapper please tell me, if it miss, i need to add it manually, and i do the fix for many clients first.

Next commit will be the add of an option into ocsms interface to select the country code and remove the duplicates

**Comment by enoch85** [comment]
Ok, so this went very wrong. No I have my conversations splitted in three:

![image](https://cloud.githubusercontent.com/assets/4511254/5607403/1a4f08cc-945b-11e4-9508-ea8d7b75bd5c.png)

And the phonenumber is +49 (hardcoded) though it should be +46 (Swedish)

```
/?phonenumber=076%20392%20XX%20XX
```

**Comment by nerzhul** [comment]
In fact, a commit introduce a bug by hardcoding german translation. I'll try to get time to write a commit to select an international prefix option and remove this problem this week...

**Comment by enoch85** [comment]
Sounds good! :)

**Comment by stagprom** [comment]
Quick and dirty workaround:
change line 56 in ocsms/lib/phonenumberformatter
		$lpnrpl = '+49$2';						// replace with +49 -xx[x[x]]-123456
in
		$lpnrpl = '+46$2';						// replace with +46 -xx[x[x]]-123456
for swedish formatting.
This works for most countries except north amerika

**Comment by enoch85** [comment]
> Quick and dirty workaround:
change line 56 in ocsms/lib/phonenumberformatter
$lpnrpl = '+49$2'; // replace with +49 -xx[x[x]]-123456
in
$lpnrpl = '+46$2'; // replace with +46 -xx[x[x]]-123456
for swedish formatting.
This works for most countries except north amerika

It still dosen´t fix the problem as expected.

![image](https://cloud.githubusercontent.com/assets/4511254/5628983/6f229f90-95ae-11e4-8fc4-9c059b5fcb98.png)

**Comment by nerzhul** [comment]
No, wait i'm thinking on the intl fix on my free hours, look at commits :)

**Comment by enoch85** [comment]
It will be interesting to see how that DB works  out, and looks. :)

**Comment by nerzhul** [comment]
it will be a select view where your select your country and the algorithm will fix the duplicates because it knows what is your country

**Comment by enoch85** [comment]
Sounds nice! Expected release?

**Comment by nerzhul** [comment]
Not at this time, many code are defined but i need to link code parts together, but i think i'll do a tagging this week

**Comment by nerzhul** [comment]
HI @enoch85  and @mozzwald 

i fixed the problem now.

Please pull master at this commit: https://github.com/nerzhul/ocsms/commit/c5a932430586d15f83e18a275c94090a2bc1e3fe

Next, go to SMS app, set a country into settings (bottom of conversations) and refresh the page.
At this time setting is not shown in the dropdown but it's into database. Page refresh is not done automaticly because i'll migrate many JS code to angular , it's the next step to cleanup JS code.
If your country is missing, please tell me, i'll add it.

Proper setting will be done when 1.4 will reach, then this week-end i hope because this issue and contact photo issue have been fixed :)

**Comment by enoch85** [comment]
@nerzhul And there my friday went from 30% good to 100% in just 2 seconds: :+1:

**Comment by mozzwald** [comment]
Choosing a country isn't being saved in the database for me. From owncloud log:

{"reqId":"89dd0172e71","app":"index","message":"Doctrine\\DBAL\\DBALException: An exception occurred while executing 'SELECT key FROM `oc_ocsms_config` WHERE `key` = ? AND `user` = ?' with params [\"country\", \"mozzwald\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key FROM `oc_ocsms_config` WHERE `key` = 'country' AND `user` = 'mozzwald'' at line 1","level":4,"time":"2015-01-09T18:33:28+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/ocsms\/set\/country"}

**Comment by enoch85** [comment]
...And I wrote that before I tested. I get a WSOD and can´t access the app anymore. Hmm...

**Comment by enoch85** [comment]
```
Fatal	index	Symfony\Component\Routing\Exception\RouteNotFoundException: Route "ocsms.sms.index" does not exist.	2015-01-09T18:41:04+00:00
Error	PHP	js file not found: script:js/public/app formfactor: serverroot:/var/www/owncloud at /var/www/owncloud/lib/private/template/resourcelocator.php#49	2015-01-09T18:35:08+00:00
Fatal	index	Exception: js file not found: script:js/public/app formfactor: serverroot:/var/www/owncloud	2015-01-09T18:35:08+00:00
Fatal	index	Symfony\Component\Routing\Exception\RouteNotFoundException: Route "ocsms.sms.index" does not exist.	2015-01-09T18:31:50+00:00
Error	PHP	js file not found: script:js/public/app formfactor: serverroot:/var/www/owncloud at /var/www/owncloud/lib/private/template/resourcelocator.php#49	2015-01-09T18:31:12+00:00
Fatal	index	Exception: js file not found: script:js/public/app formfactor: serverroot:/var/www/owncloud	2015-01-09T18:31:12+00:00
Error	PHP	js file not found: script:js/public/app formfactor: serverroot:/var/www/owncloud at /var/www/owncloud/lib/private/template/resourcelocator.php#49	2015-01-09T18:30:54+00:00
Fatal	index	Exception: js file not found: script:js/public/app formfactor: serverroot:/var/www/owncloud	2015-01-09T18:30:54+00:00
Error	PHP	js file not found: script:js/public/app formfactor: serverroot:/var/www/owncloud at /var/www/owncloud/lib/private/template/resourcelocator.php#49	2015-01-09T18:28:42+00:00
Fatal	index	Exception: js file not found: script:js/public/app formfactor: serverroot:/var/www/owncloud	2015-01-09T18:28:42+00:00
```

**Comment by nerzhul** [comment]
Hmm app seems to be broken somewhere. For @mozzwald problem https://github.com/nerzhul/ocsms/commit/f76a37663584bdb6a971f7b203e732d9dd5b12df fixes the SQL syntaxes, sorry i forget some ` for MySQL :)

For the PHP js file not found, this is strange, i haven't this issue, it's related to angular.js i think.
I need to fix another issue related to fetching conversation before

**Comment by enoch85** [comment]
Also got this:

```
Error	PHP	Class 'OCA\OcSms\Lib\CountryCodes' not found at /var/www/owncloud/apps/ocsms/lib/phonenumberformatter.php#43	2015-01-09T18:49:36+00:00
Error	PHP	Missing argument 2 for OCA\OcSms\Lib\PhoneNumberFormatter::format(), called in /var/www/owncloud/apps/ocsms/appinfo/ocsmsapp.php on line 140 and defined at /var/www/owncloud/apps/ocsms/lib/phonenumberformatter.php#41	2015-01-09T18:49:36+00:00
```

**Comment by nerzhul** [comment]
I forget argument and you have right PHP infos :)

Commit https://github.com/nerzhul/ocsms/commit/84db79a30031daaa285753dbf0ed616f70637def fix it.

But for countrycodes.php the file was here: https://github.com/nerzhul/ocsms/blob/master/lib/countrycodes.php

please look at your lib folder and check you have the right app, not stable but master branch

**Comment by mozzwald** [comment]
@nerzhul no more syntax error but the country choice is not saved in db. ocsms_config table is empty

**Comment by nerzhul** [comment]
It seems this is a problem with angular.js

https://github.com/nerzhul/ocsms/commit/642f78e859f6328df94aa9de1530553512af29cf remove one angular controller and may fix the db insert

**Comment by nerzhul** [comment]
@mozzwald can you confirm that the problem is fixed now ? i think this is good and i need to learn more angular.js subtilities, because OC uses it and i haven't before this project :)

**Comment by enoch85** [comment]
@nerzhul I deleted the oc_sms tables in MySQL because I got a white screen trying to connect to the app. Now I get this:

```
An exception occurred while executing 'SELECT sms_address FROM oc_ocsms_smsdatas WHERE user_id = ? AND sms_mailbox IN (?,?)': SQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_ocsms_smsdatas' doesn't exist
```

Is there any way to force oc sms to create new tables?

**Comment by nerzhul** [comment]
@enoch85 disable and reenable the app must do the trick i think

**Comment by mozzwald** [comment]
@nerzhul country is now saved in db

**Comment by nerzhul** [comment]
Please go to https://github.com/nerzhul/ocsms/commit/100308b9ec01f6482cc09239df5e61a9acd2895e 
and tell me if you got problems please

**Comment by mozzwald** [comment]
no problems for me so far at 100308b

**Comment by nerzhul** [comment]
That's good ! we can think 1.4 can be on rails :)
I'll finish avatars and angular JS migration and i tag 1.4, next we can do more things on android client and server side

**Comment by nerzhul** [comment]
@mozzwald can i close this issue ?

**Comment by mozzwald** [comment]
It's a done deal! Thanks for the hard work :)
