### ISSUE TITLE
Add sort by date or alphabetical option to left pane

### ISSUE THREAD

**Issue by mozzwald** [nerzhul/ocsms#16]
It would be nice to have 'sort by' option at the top of the left pane to choose by date or alphabetical.

**Comment by viki53** [comment]
Sorting in general would be nice: current listing doesn't match my phone's date sorting.

Any idea where to look if I try to implement this?

**Comment by nerzhul** [comment]
The list is generated by an AJAX call. Look at the JS source. Also add a new option to store storing (in same area than language option) and load it before loading the contacts, and then do what you want with the list :)

**Comment by nerzhul** [comment]
This is implemented since 1.11.0 release or lesser i think, i close this issue
