### ISSUE TITLE
Add a delete button to delete messages or converstions

### ISSUE THREAD

**Issue by enoch85** [nerzhul/ocsms#21]
As it is today you can only read messages. But it should also be possible to delete:
- [x] Whole conversations
- [x] Separate SMS

The most simple soulution would be to use the svg-icon that ownCloud uses to delete things. Of course this should be synced with [Also sync deleted messages with 2-way sync](https://github.com/nerzhul/ownCloud-SMS-App/issues/7)

**Comment by nerzhul** [comment]
I thought about your issue. At this time it's possible to add a button for deleting conversation and SMS but i will not be removed from phone and at next phone sync the SMS will be resynced if present on the phone but not the app.

**Comment by enoch85** [comment]
Better to wait for 2 way sync.

**Comment by nerzhul** [comment]
@enoch85 first step done :)

**Comment by enoch85** [comment]
@nerzhul Nice! When this is done I will start using the app again. :)

**Comment by nerzhul** [comment]
https://github.com/nerzhul/ocsms/commit/13d5e9ff268c2fb4aee04cc1a382ec26152500ae

It's finished. I rewrite/move 80% of all app JS to use Angular properly, this permit to do great things like delete messages atomicly and do a proper backend action . It's now solved

**Comment by enoch85** [comment]
Thanks!
