### ISSUE TITLE
Mobile CSS is wrong

### ISSUE THREAD

**Issue by enoch85** [nerzhul/ocsms#23]
http://goo.gl/rhvE3F

You can't swipe to see the conversations.

**Comment by nerzhul** [comment]
i don't remember the issue and picture wasn't present anymore. Can you resend me the picture please ?

**Comment by enoch85** [comment]
I don't use this app anymore. Buy it was that you can't swipe to see the conversations...

**Comment by nerzhul** [comment]
okay, i haven't this issue anymore as it seems on my mobile phone. I close the issue
