### ISSUE TITLE
Conversations divided in 2 conversations

### ISSUE THREAD

**Issue by gringo1er** [nerzhul/ocsms#30]
some conversations are cut in two "conversations": one contains all words sorted by contact, and the other contains my words. The apparent phone number changes: the contacts phone numbers begin with +33 (french indicative, it's normal my contacts are as french as I am), and the other conversation begins with +49 (Germany??), followed with the right phone number.

All my OC zone parameters are France or Paris.

Thanxx

**Comment by nerzhul** [comment]
In fact, the current PhoneNumberFormatter replace prefix with +49, because it's a german fix. I will fix this problem soon by introducing a variable into app settings to set the current prefix by country

**Comment by nerzhul** [comment]
https://github.com/nerzhul/ocsms/commit/ab3bd8718eba817bba14c6bddc8fef3ea9374bbc

Work in progress, i will add option today or tomorrow into ocsms app

**Comment by gringo1er** [comment]
Hello
Could you explain where phone numbers are stored inside the database? I would like to try to change +49 into +33 for archived sms, with mysql workbench....
Thanx

**Comment by nerzhul** [comment]
Hi, i fixed the problem now.

Please pull master at this commit: https://github.com/nerzhul/ocsms/commit/c5a932430586d15f83e18a275c94090a2bc1e3fe

Next, go to SMS app, set a country into settings (bottom of conversations) and refresh the page.
At this time setting is not shown in the dropdown but it's into database. Page refresh is not done automaticly because i'll migrate many JS code to angular , it's the next step to cleanup JS code.
If your country is missing, please tell me, i'll add it.

**Comment by gringo1er** [comment]
Hello. I have replaced ocsms. After a quick upgrade process (when OC rebooted), when I click on SMS tab, I obtain a white page.
At the dev console, I obtain that message: 
Failed to load resource: net::ERR_CACHE_MISS, and an error 500
I'm sorry...... i imagine that you worked hard to solve that issue

**Comment by gringo1er** [comment]
A new install of the former version, and the sms tab is back (with the issue, of course).

**Comment by nerzhul** [comment]
Have you selected a lang, click on validate and refresh the page ?

**Comment by gringo1er** [comment]
no, impossible because the page was totally blank. No conversation, no menu.....

**Comment by nerzhul** [comment]
That's strange. Can you remove app and reinstall it properly ? I think there is a problem somewhere in your installation

**Comment by gringo1er** [comment]
Already done. I have removed it (with an action on the "disable" button). And reinstalled it. Same issue. I removed once again and installed the former version, it worked (with the known prefix issue of course).
On your last message you gave a link to the contain of a file, not to the commit. Maybe I downloaded a wrong version of the commit.

**Comment by nerzhul** [comment]
@gringo1er sorry for that commit.
I do many commits yesterday and today to improve app development and stability. Can you confirm setting language and refreshing main page fix the duplicate conversations ?

**Comment by gringo1er** [comment]
tested with the fb8003faf2 commit... Sorry, but the sms tab doesn't charge (or doesn't stop charging, but doesnt finish charging). Due to the absence of the menu, I can't verify the language setting.....

New stop, news reinstall of the 1.3.1 version, new start.....

I don't know what to say to help you....   :°(

**Comment by nerzhul** [comment]
Rmrlmlr, it's very strange. Why is this working for me but not for you.
Have you got JS errors ? apache errors ? php errors ?

**Comment by gringo1er** [comment]
Here is an extract of owncloud error log

Error	PHP	js file not found: script:js/public/app formfactor: serverroot:/var/www/owncloud at /var/www/owncloud/lib/private/template/resourcelocator.php#49	
Fatal	index	Exception: js file not found: script:js/public/app formfactor: serverroot:/var/www/owncloud

Here is the correspondant extrat of IE console

HTML1524: DOCTYPE HTML5 non valide. Utilisez plutôt le formulaire interopérable « <!DOCTYPE html> ».
Fichier : http_500.htm, ligne : 1, colonne : 1   (in french, sorry for that)

And hereafter the error appearing with Chrome console
![capture2](https://cloud.githubusercontent.com/assets/9809622/5695176/ea8a1c5a-9994-11e4-8caa-1e90644e5d64.JPG)
 
No specific error on apache and php logs...
I think if we could go over the error 500, we could find other traces..

**Comment by nerzhul** [comment]
Hmm another user report this error, i don't know at this time where does it comes from but i'll try to fix it faster.
No problem for french, i'm french too

**Comment by nerzhul** [comment]
In last setup i added empty js/public/app.js.
 https://github.com/nerzhul/ocsms/commit/555d8f1ed117121710cc4e41b48aaad215768708

Can you try this commit ?

**Comment by nerzhul** [comment]
Oh, i found the issue i think.

You need to have app framework enabled. It's because i include a dependency.

https://github.com/nerzhul/ocsms/commit/1a1e7000f275edb384e06b8297ae6fea328fe149

**Comment by nerzhul** [comment]
Ok go to https://github.com/nerzhul/ocsms/commit/100308b9ec01f6482cc09239df5e61a9acd2895e
And tell me

**Comment by gringo1er** [comment]
Ok. Where to include the framework app? I mean, it's not a native app, so I found 2 versions of app framework on app.owncloud.com. Witch version do I need to download?

**Comment by nerzhul** [comment]
https://apps.owncloud.com/content/show.php/App+Framework?content=158433 i think. But normally you have app framework included in your app list, no ?

**Comment by gringo1er** [comment]
how how how!!! Dear Santa! It works! After a quick check, conversations with the same callers , splitted with the preview version, have gathered!

Maybe we could close.... Good job my dear.

Nota: a request.... Maybe you could add a function to suppress conversations? With a bin located near each conversation?

**Comment by enoch85** [comment]
IT WORKS! :beers:

**Comment by enoch85** [comment]
But it flooded my log with errors of 'undefined index' before setting the country in the menu.

```
Error	PHP	Undefined index: 073687XXXX at /var/www/owncloud/apps/ocsms/controller/smscontroller.php#217	2015-01-12T22:45:22+00:00
Error	PHP	Undefined index: 073413XXXX at /var/www/owncloud/apps/ocsms/controller/smscontroller.php#217	2015-01-12T22:45:22+00:00
Error	PHP	Undefined index: +4670486XXXX at /var/www/owncloud/apps/ocsms/controller/smscontroller.php#217	2015-01-12T22:45:22+00:00
Error	PHP	Undefined index: 073687XXXX at /var/www/owncloud/apps/ocsms/controller/smscontroller.php#217	2015-01-12T22:45:11+00:00
Error	PHP	Undefined index: 073413XXXX at /var/www/owncloud/apps/ocsms/controller/smscontroller.php#217	2015-01-12T22:45:11+00:00
Error	PHP	Undefined index: 070449XXXX at /var/www/owncloud/apps/ocsms/controller/smscontroller.php#217	2015-01-12T22:45:11+00:00
Error	PHP	Undefined index: 0701601XXXX at /var/www/owncloud/apps/ocsms/controller/smscontroller.php#217	2015-01-12T22:45:11+00:00
Error	PHP	Undefined index: +467607XXXX at /var/www/owncloud/apps/ocsms/controller/smscontroller.php#217	2015-01-12T22:45:11+00:00
Error	PHP	Undefined index: +467048XXXX at /var/www/owncloud/apps/ocsms/controller/smscontroller.php#217	2015-01-12T22:45:11+00:00
Error	PHP	Undefined index: 073687XXXX at /var/www/owncloud/apps/ocsms/controller/smscontroller.php#217	2015-01-12T22:45:01+00:00
Error	PHP	Undefined index: 07341XXXX at /var/www/owncloud/apps/ocsms/controller/smscontroller.php#217	2015-01-12T22:45:01+00:00
Error	PHP	Undefined index: 070449XXXX at /var/www/owncloud/apps/ocsms/controller/smscontroller.php#217	2015-01-12T22:45:01+00:00
```

And then this:
```
Error	PHP	call_user_func() expects parameter 1 to be a valid callback, class 'OCA\OcSms\Db\Config' not found at /var/www/owncloud/lib/public/appframework/db/mapper.php#250
```

**Comment by nerzhul** [comment]
Hi @enoch85 thanks for your report. I fix the 1st warning in commit https://github.com/nerzhul/ocsms/commit/759dadbd607be6eb19b0cc4f301e9bf70c07daa6 (forget to test this array).

For the second, please verify you have db/configmapper.php.

Issue closed ! thanks to all
