### ISSUE TITLE
Cropped text messages from iOS.

### ISSUE THREAD

**Issue by torer** [nerzhul/ocsms#32]
Hey,
when I get sms from iphone with emoticon, on page  appears only text in front of emoticon.
Regards 
Torer
![sms](https://cloud.githubusercontent.com/assets/2254106/5598159/0b5ed9b0-92b1-11e4-97e2-f5014a8fd300.png)

android app: 0.16.0
owncloud: 7.0.4-3 
ocsms: 1.3.2

**Comment by nerzhul** [comment]
Hi,
thanks for your bug report. can you look into your database to check what is present for this message into oc_ocsms_smsdatas ?

**Comment by torer** [comment]
Surley:
id: 454
user_id: xxxxx
added: 0000-00-00 00:00:00
lastmodified: 0000-00-00 00:00:00
sms_id: 555
sms_address: +48xxxxxxxxx
sms_msg: Dziekuje
sms_date: 1420115964156
sms_flags: 00
sms_mailbox: 0
sms_type: 1

Database:
mariadb-server  5.5.40-0ubuntu0.14.04.1
DEFAULT CHARACTER SET latin1

**Comment by nerzhul** [comment]
Then this is the only message present in your phone, maybe second part is splited into MMS on Android

**Comment by torer** [comment]
Hmm, it's looking like sms. In message details i see "SMS", but this emoticons are small images, not text. When i send this sms via mail, i got weird char. In html view i see icon, but in source is something like "đ" or small rectangle. 

When my friend will come back from holiday, i'll check how she sent messages like this.

When you send message from mobile to server, app is using POST request to some kind of webservice?
Maybe can i log this request and check, if the message is cutted on server or in android app?
![sms](https://cloud.githubusercontent.com/assets/2254106/5599384/a8927a2a-92c5-11e4-8ac8-4fc1b7aeff46.png)

**Comment by torer** [comment]
And, when i'm trying forward message via sms, i got warning "This message contain special chars". This small image must be a some shit included in font.

**Comment by nerzhul** [comment]
Yes, i think it's related to message content. OwnCloud SMS sync the raw data of the message, then there is no issue for us here, but a problem in your real message

**Comment by nerzhul** [comment]
It's a problem into SMS client, not into ocsms. close issue
