### ISSUE TITLE
contacts photos mixed

### ISSUE THREAD

**Issue by gringo1er** [nerzhul/ocsms#33]
Hello!
With the new (and excellent) 1.3.6 version, I have a little issue: some sms are matched with the photos of contacts stored on OC contact functions.

But they are mixed.... For most of them, photos don't match with the right author of conversations

**Comment by gringo1er** [comment]
Oh.... After a reboot of my server, the bug disappeared, each photo matches with the right conversation..... Strange... I close the issue

**Comment by gringo1er** [comment]
.... but when I refresh the page (with F5), images mixed again. I reopen the issue (closed too quickly)

**Comment by nerzhul** [comment]
The avatar code isn't finished yet, 1.3.6 isn't production usable, i'll look at this strange bug

**Comment by nerzhul** [comment]
Please use https://github.com/nerzhul/ocsms/commit/a0c820ab820600ee076a5b05b102f5624d93fc1a and tell me. I'll release 1.4.0 today, i don't found any algorithm bug but i added fixes which may fix you problem.

I'll let your ticket opened

**Comment by gringo1er** [comment]
No, I'm sorry
The bug remains present, but with Google Chrome only....
At the first connection, photos match with conversations. But after an action on F5 (or reload page, or action on SMS logo), photos don't match with conversations anymore... If I close and reopen the SMS tab with my browser, it is like if I open for the first time.

When I follow the same test and process, with IE, the bug is gone, everything seems to work.

**Comment by nerzhul** [comment]
Old issue.
