### ISSUE TITLE
Missing App from webview

### ISSUE THREAD

**Issue by delumerlino** [nerzhul/ocsms#34]
Hi, just updated ocsms from 1.3 to 1.4 on my owncloud 7.0.4.
The application is listed and enabled in the application list, but my user is unable to access to it (it is not listed in the published apps for user).
Thank you

**Comment by nerzhul** [comment]
Hi @delumerlino ,
it's very strange, rights haven't changed between 1.3 to 1.4.
Can you disable and enable app ? Have you filtered by groups ?

**Comment by delumerlino** [comment]
Hi, I rewrote the permissions in the folder and tried to disable/enable the
app from Webapps but nothing changed...
Also tried to reboot my Ubuntu station but nothing happened.

When installed, owncloud did the database update, so it seems to be
installed...

TY
Il 19/Gen/2015 12:26 "nerzhul" <notifications@github.com> ha scritto:

**Comment by nerzhul** [comment]
Do you see something in owncloud.log or apache logs ?

Application doesn't appear in app menu for user, right ?

**Comment by delumerlino** [comment]
Thank you,
I can see only this in owncloud.log:
{"app":"ocsms","message":"Can not enable the OcSms app because the App
Framework App is disabled","level":3,"time":"2015-01-19T11:40:18+00:00"}
Apache.log is normal.

And yes, the application doesn't appear in the app menu for each user.

Regards

Andrea

2015-01-19 12:38 GMT+01:00 nerzhul <notifications@github.com>:

> Do you see something in owncloud.log or apache logs ?
>
> Application doesn't appear in app menu for user, right ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nerzhul/ocsms/issues/34#issuecomment-70480595>.
>



-- 
--------------------------------------------------------------------------
*P *Prima di stampare, pensa all'ambiente ** Think about the environment

**Comment by nerzhul** [comment]
Then, enable the app framework, like the log said :)

**Comment by delumerlino** [comment]
Thank you! Sorry but haven't read about FW :)

2015-01-19 12:46 GMT+01:00 nerzhul <notifications@github.com>:

> Then, enable the app framework, like the log said :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nerzhul/ocsms/issues/34#issuecomment-70481400>.
>



-- 
--------------------------------------------------------------------------
*P *Prima di stampare, pensa all'ambiente ** Think about the environment

**Comment by nerzhul** [comment]
no problem

**Comment by cwmilwaukee** [comment]
I appologize if I missed something but I'm having the same issue as delumerlino.  From what I can tell, in Owncloud 7, the app framework is built into Owncloud.  I remember in some of the older versions app framework would show up in the app menu.  Is there another way to activate the internal app framework?

Thanks a lot for any help you can provide.

**Comment by nerzhul** [comment]
Ok, i found the issue, it's due to 6.0 compat.

**Comment by nerzhul** [comment]
Fixed in tag 1.4.1, sorry 

https://github.com/nerzhul/ocsms/tree/v1.4.1

**Comment by cwmke** [comment]
No trouble at all.  Thanks for the quick fix.
