### ISSUE TITLE
Can not enable the OcSms app because the App Framework App is disabled

### ISSUE THREAD

**Issue by RookieIV** [nerzhul/ocsms#35]
I installed ocsms on my Owncloud 7.0.4 (https = on). PHP Version is unknown.

I get following error: "Can not enable the OcSms app because the App Framework App is disabled"

This is an excerpt of the owncloud.log

...
$
{"reqId":"54c5ed6866f25","app":"ocsms","message":"Can not enable the OcSms app because the App Framework App is disabled","level":3,"time":"2015-01-26T07:31:52+00:00","method":"POST","url":"\/owncloud\/index.php\/core\/ajax\/translations.php"}
{"reqId":"54c5ed6903c0b","app":"ocsms","message":"Can not enable the OcSms app because the App Framework App is disabled","level":3,"time":"2015-01-26T07:31:53+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2F$
{"reqId":"54c5ed69400a2","app":"ocsms","message":"Can not enable the OcSms app because the App Framework App is disabled","level":3,"time":"2015-01-26T07:31:53+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/ajax\/share.php?fetch=getItemsSharedStat$
{"reqId":"54c5ed6c278f9","app":"ocsms","message":"Can not enable the OcSms app because the App Framework App is disabled","level":3,"time":"2015-01-26T07:31:56+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/help"}
{"reqId":"54c5ed6cb4dc2","app":"ocsms","message":"Can not enable the OcSms app because the App Framework App is disabled","level":3,"time":"2015-01-26T07:31:56+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/js\/oc.js?v=4d742f3ec26b3bafbc63c30655d2$
{"reqId":"54c5ed6d41012","app":"ocsms","message":"Can not enable the OcSms app because the App Framework App is disabled","level":3,"time":"2015-01-26T07:31:57+00:00","method":"POST","url":"\/owncloud\/index.php\/core\/ajax\/translations.php"}
{"reqId":"54c5ed6e9b0e0","app":"ocsms","message":"Can not enable the OcSms app because the App Framework App is disabled","level":3,"time":"2015-01-26T07:31:58+00:00","method":"GET","url":"\/owncloud\/cron.php"}
{"reqId":"54c5ed6ec0da2","app":"ocsms","message":"Can not enable the OcSms app because the App Framework App is disabled","level":3,"time":"2015-01-26T07:31:58+00:00","method":"POST","url":"\/owncloud\/index.php\/core\/ajax\/translations.php"}
{"reqId":"54c5ed6f09cf2","app":"ocsms","message":"Can not enable the OcSms app because the App Framework App is disabled","level":3,"time":"2015-01-26T07:31:59+00:00","method":"GET","url":"\/owncloud\/index.php\/avatar\/thomas\/32?requesttoken=93a92c6e164187$
{"reqId":"54c5ed6fc9463","app":"ocsms","message":"Can not enable the OcSms app because the App Framework App is disabled","level":3,"time":"2015-01-26T07:31:59+00:00","method":"GET","url":"\/owncloud\/index.php\/avatar\/thomas\/128?requesttoken=93a92c6e16418$
{"reqId":"54c5ed75d8e1d","app":"ocsms","message":"Can not enable the OcSms app because the App Framework App is disabled","level":3,"time":"2015-01-26T07:32:05+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/admin"}
{"reqId":"54c5ed76f3381","app":"ocsms","message":"Can not enable the OcSms app because the App Framework App is disabled","level":3,"time":"2015-01-26T07:32:06+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/js\/oc.js?v=4d742f3ec26b3bafbc63c30655d2$
{"reqId":"54c5ed777e6ea","app":"ocsms","message":"Can not enable the OcSms app because the App Framework App is disabled","level":3,"time":"2015-01-26T07:32:07+00:00","method":"POST","url":"\/owncloud\/index.php\/core\/ajax\/translations.php"}
{"reqId":"54c5ed791ca97","app":"ocsms","message":"Can not enable the OcSms app because the App Framework App is disabled","level":3,"time":"2015-01-26T07:32:09+00:00","method":"GET","url":"\/owncloud\/cron.php"}
{"reqId":"54c5ed7944468","app":"ocsms","message":"Can not enable the OcSms app because the App Framework App is disabled","level":3,"time":"2015-01-26T07:32:09+00:00","method":"POST","url":"\/owncloud\/index.php\/core\/ajax\/translations.php"}
{"reqId":"54c5ed797fd4a","app":"ocsms","message":"Can not enable the OcSms app because the App Framework App is disabled","level":3,"time":"2015-01-26T07:32:09+00:00","method":"GET","url":"\/owncloud\/index.php\/avatar\/thomas\/128?requesttoken=93a92c6e16418$
{"reqId":"54c5ed79de359","app":"ocsms","message":"Can not enable the OcSms app because the App Framework App is disabled","level":3,"time":"2015-01-26T07:32:09+00:00","method":"GET","url":"\/owncloud\/index.php\/avatar\/thomas\/32?requesttoken=93a92c6e164187$
{"reqId":"54c5ed7a5e95c","app":"ocsms","message":"Can not enable the OcSms app because the App Framework App is disabled","level":3,"time":"2015-01-26T07:32:10+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/ajax\/checksetup"}
...

**Comment by nerzhul** [comment]
have you got the AppFramework enabled ?

**Comment by nerzhul** [comment]
Issue found. I do a new release, it's a problem with 6.0 compat

**Comment by nerzhul** [comment]
Hi,
it's fixed into 1.4.1, tagged now on github

https://github.com/nerzhul/ocsms/tree/v1.4.1

Sorry for the inconvenience
