### ISSUE TITLE
"No app name specified" when try to enable ocsms v1.4 in my owncloud apps webpage

### ISSUE THREAD

**Issue by ericfont** [nerzhul/ocsms#36]
I downloaded your v1.4 zip and opened my owncloud apps webpage, press the Enable button, but it fails to enable and says: "No app name specified".  Also when looking up the link "See application page on apps.owncloud.com" (http://apps.owncloud.com/content/show.php?content=ocsms) it has an empty app page with text "Content not found".  

Server

    ownCloud version: 7.0.4
    PHP version: 5.6.5
    HTTPd server: Apache 2.4.10
    HTTPS: openssl 1.0.1l

Client (irrelevant for this issue)

Content of /owncloud/data/owncloud.log

Warning	core	XCache opcode cache will not be cleared because "xcache.admin.enable_auth" is enabled.	2015-01-26T10:11:10+00:00
Error	core	No app name specified	2015-01-26T10:03:13+00:00
Fatal	core	Invalid OCS content returned for app ocsms	2015-01-26T10:03:13+00:00
Error	core	No app name specified	2015-01-26T10:00:43+00:00
Fatal	core	Invalid OCS content returned for app ocsms	2015-01-26T10:00:43+00:00
Error	core	No app name specified	2015-01-26T10:00:37+00:00
Fatal	core	Invalid OCS content returned for app ocsms	2015-01-26T10:00:37+00:00

**Comment by nerzhul** [comment]
I see you use PHP 5.6, can you confirm that the bug is present with PHP 5.5 and 5.4 (I'm using 5.4 ATM, but i need to upgrade)

**Comment by nerzhul** [comment]
you are right, application name is different on app store.

But content=ocsms must be content=167289 . I don't know atm where does this bug comes from.

Have you tested with PHP 5.5 and 5.4 ?

**Comment by ericfont** [comment]
I haven't tested with php 5.5 or 5.4, and I don't really know how to easily downgrade packages on arch linux easily, and don't have an earlier packages for php cached.

**Comment by nerzhul** [comment]
php 5.5 and 5.4 are in AUR

aur/php54 5.4.34-2 (1)

**Comment by ericfont** [comment]
just finished compiling php54 on yaourt, but then halted install due to a bunch of dependencies that were messed up, and I don't feel like redoing my server's config now.  

However, I would be willing to try to setup a new VM server with same config just with php54 instead...not today, but let me know if you need me to do that to test.  Or better you if you want to send me some simple patches I can test on my php 5.6.5 setup.

**Comment by Knah-Tsaeb** [comment]
In Archlinux, you can use Downgrader app https://aur.archlinux.org/packages/downgrader/ for search older package and install it.

**Comment by nerzhul** [comment]
Unfortunately i haven't any solution at this time for this problem and i need to fix an angular.js problem in 1.4.1 :s

**Comment by ericfont** [comment]
Well I installed your latest version, this time following the directions here https://apps.owncloud.com/content/show.php/SMS+app?content=167289, which stated to rename the folder to ocsms, and that worked.  So that was most likely the problem.  

Anyway, please copy those directions about renaming the folder into both your readme and wiki so that people like me who found your app through f-droid or somewhere else other than apps.owncloud.com know how to install.

**Comment by nerzhul** [comment]
@ericfont thanks for the tip, i remember  that was this issue some months ago. I'll add it to apps.owncloud.com description
