### ISSUE TITLE
Exception: js file not found: script:js/public/app formfactor: serverroot:/var/secure/owncloud 

### ISSUE THREAD

**Issue by RookieIV** [nerzhul/ocsms#37]
Hello,

Sorry for beeing so annoying. The Issue #35 is solved. But there is another problem.

I installed the app, everything worked fine. But when i start it, i get a blank page an following errors.

{"reqId":"54c637de1e4d7","app":"index","message":"Exception: js file not found: script:js\/public\/app formfactor: serverroot:\/var\/secure\/owncloud","level":4,"time":"2015-01-26T12:49:34+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/ocsms\/"}
{"reqId":"54c637de1e4d7","app":"PHP","message":"js file not found: script:js\/public\/app formfactor: serverroot:\/var\/secure\/owncloud at \/var\/secure\/owncloud\/lib\/private\/template\/resourcelocator.php#49","level":3,"time":"2015-01-26T12:49:34+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/ocsms$

Thank you for helping.

**Comment by nerzhul** [comment]
erf.... i'll look at this now, sorry for the inconvenience. It's related to angular.js and appear sometimes, but i thought i resolved it.

**Comment by nerzhul** [comment]
I do a clean owncloud install and have the problem (the problem is not present on my instance...)
I'll fix it soon

**Comment by nerzhul** [comment]
Okay, it's fixed, it's an issue with 6.0 compat and angular.js 1.2. I revert back angular to 1.1.5 and remove appframework angular use.

Please use tag 1.4.2
