### ISSUE TITLE
Lot of timeout with nginx

### ISSUE THREAD

**Issue by flyinva** [nerzhul/ocsms#38]
Server

    ownCloud version: 7.0.4
    PHP version: 5.4.36
    HTTPd server: nginx
    HTTPS: yes

Client

    Android version: 4.4
    Phone: HTC Wildfire
    ownCloud SMS app version: 1.4.1

Content of /owncloud/data/owncloud.log : nothing in owncloud.log

I have a lot of error message in nginx/error.log concerning timeout

    2015/01/27 22:32:16 [error] 26577#0: *6559 upstream timed out (110: Connection timed out) while reading response header from upstream, client: X.X.X.X, server: cloud.server.net, request: "GET /index.php/apps/ocsms/get/conversation?phoneNumber=%2B3399999999 HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock", host:…

I've change `fastcgi_read_timeout` to 120 without any success

**Comment by nerzhul** [comment]
Hi @flyinva , can you upgrade to 1.4.2 and do a test. Problems are with owncloud in general or only with ocsms app ?
Upgrade 1.4.2 can help

**Comment by nerzhul** [comment]
ping ?

**Comment by flyinva** [comment]
Sorry for the delay. It sesms OK since upgrade to OC 8.0 and ocsms 0.17.0

**Comment by nerzhul** [comment]
Ok, thanks, i close it
