### ISSUE TITLE
indexes on database

### ISSUE THREAD

**Issue by martin-rueegg** [nerzhul/ocsms#47]
i was quite astonished to see no indexes on the database. i would suggest the following.

(numbers in the index rows reflect the ordinal position of the field within the index

### \*PREFIX\*ocsms_config
function | key | user | value
-----------|-------|-------|--------
set | x | x
hasKey | x | x
getKey | x | x
**suggested index** |
PRIMARY | 2 | 1
:heavy_exclamation_mark: this is not possible, unless the datatype of *key* is changed. but i don't see any reason for a mediumtext in the first place. i guess varchar(255) would be enough.

### \*PREFIX\*ocsms_smsdatas
function | user_id | sms_mailbox | sms_address | sms_date
-----------|-----------|--------------------|-------------------|---------------
getAllIds | x
getAllIdsWithStatus | x
getLastTimestamp | x | | | max()
getAllPeersPhoneNumbers | x | x
getAllPhoneNumbersForFPN | x | x
getAllMessagesForPhoneNumber| x | x | x | >
countMessagesForPhoneNumber | x | x | x | count()
getLastMessageTimestampForAllPhonesNumbers | x | x
getNewMessagesCountForAllPhonesNumbers | x | x | group by | >
writeToDB | x
**suggested index** |
ocsms_user_addr_date_mbox_index | 1 | 4 | 2 | 3
ocsms_user_mbox_index | 1 | 2

### \*PREFIX\*ocsms_user_datas
function | user_id | datakey | datavalue
-----------|-----------|--------------------|-------------
getLastReadDate | x | | max()
setLastReadDate | x | x
**suggested index** |
ocsms_user_key_index | 1 | 2
ocsms_user_value_index | 1 |  | 2

if there is a consent on these indices i will try to make an update script. if anyone can give me a hint on where to start it would be appreciated.

**Comment by nerzhul** [comment]
It would be a good idea. Is this possible using appinfo/database.xml
