### ISSUE TITLE
SMSs to same person shows as different conversations

### ISSUE THREAD

**Issue by jas4711** [nerzhul/ocsms#50]
For some conversations, it seems there are two entries for the same person.  I see that the urls are '/owncloud/index.php/apps/ocsms/?phonenumber=+12 34 56 789#' vs '/owncloud/index.php/apps/ocsms/?phonenumber=+123456789#' -- notice the additional space.  I don't know where the space comes from, but I assume it should be stripped, and that both conversations show as the same conversation?

I'm using ownCloud 8, ocsms git 75e3e409acc7c2fb288c377c8becf411acc0acc4 and ownCloud-SMS 0.17.0 from fdroid.

**Comment by nerzhul** [comment]
Hi @jas4711 this is already stripped, i relook at phone number formatter

**Comment by jas4711** [comment]
Hi.  Not sure I follow -- are you saying this is fixed already?  How to test?

**Comment by nerzhul** [comment]
I said normally this bug cannot occur because it's already fixed. Have you got selected a language in the web interface settings ?

**Comment by jas4711** [comment]
I can't seem to be able to change the language -- it is the default 'Algeria' and I try to switch to Sweden and click the button, but whenever I go into the SMS app again it is still Algeria.  Any ideas?

Btw, shouldn't it use the language setting from ownCloud global?

**Comment by nerzhul** [comment]
have you got an error in your apache/php logs ?

**Comment by jas4711** [comment]
Plenty of them... what should I look for?    Looking for 'sms' doesn't find anything recent though.

Is it possible to force a redownload of everything?  Disable+uninstall oc app, uninstall android app, install oc app, install android app?

**Comment by nerzhul** [comment]
Give me an extract please

**Comment by nroach44** [comment]
I'm getting the same issue and the only thing showing in the apache logs when I try to set an option is
```
192.168.0.62 - - [14/Feb/2015:12:19:46 +0800] "POST /index.php/apps/ocsms/set/country HTTP/1.1" 200 741 "https://sync.haven/index.php/apps/ocsms/" "Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Geck
o/20100101 Firefox/31.0 Iceweasel/31.4.0"
```

**Comment by nerzhul** [comment]
@nroach44 keeping the language in the dropdown doesn't work ?

**Comment by nroach44** [comment]
No, it isn't retained.

**Comment by nerzhul** [comment]
I'll look at this issue first

**Comment by nerzhul** [comment]
@nroach44 fixed by https://github.com/nerzhul/ocsms/commit/77a9e9cccf306d87d468b4edc3079b80e1a7021e

@enoch85 @jas4711 can you pull the last -stable application please ?

**Comment by jas4711** [comment]
Not exactly sure what to test -- but selecting 'Sweden' now retains the setting next time I enter the SMS app.  Is that what you wanted me to check?

**Comment by jas4711** [comment]
Also, this seems to fix the mixed-conversation issue -- however changing between language is really slow (does it reparse all sms'es?) so I never had the patience to wait before, and there were no visual cues indicating it was working.

**Comment by nerzhul** [comment]
i only fix the language option loading. Changing the langage is instant, but we don't reload contact list at this time, maybe it will be an improvement. I think you reload the page to see the changes, no ?

**Comment by jas4711** [comment]
Yes you are right -- change only happens on reload.  So, as far as I can tell, with this fix, and after chosing the correct country, things work.  Isn't there an algorithm that works even without supplying country-information?  That seems a bit fragile.  Maybe I have local phone numbers in multiple country prefixes -- see no reason why that couldn't work too.

Thanks for working on the app!  It is quite nice seeing all SMSs in OC.

**Comment by nerzhul** [comment]
in fact we couldn't have a better way to dedup contacts. The app needs to know in which country you are to fix the dedup contacts between local numbers and intl numbers. I think adding a popup if the country is not set could help.
Also, i will look at contact list reload when you change the country

**Comment by nerzhul** [comment]
I close the issue, then

**Comment by jas4711** [comment]
Couldn't you strip all known +xxx international prefixes, and leading zeros, and then match on the remaining phone number?  Then there is no need to specify the particular +46 etc.

**Comment by nerzhul** [comment]
No because some countries doesn't work like many european countries

**Comment by jas4711** [comment]
Okay.  Anyway, it now works for me!
