### ISSUE TITLE
Allow two-way sync

### ISSUE THREAD

**Issue by nroach44** [nerzhul/ocsms#51]
Enhancement

Add an option to allow downloading the conversations from the server and syncing them on the phone - I just upgraded and it would be nice to sync all my old conversations.

**Comment by nerzhul** [comment]
Hi, thanks for your issue. The goal of the next release is to restore messages

**Comment by nroach44** [comment]
Okay, thanks!

**Comment by enoch85** [comment]
Dup of #24

**Comment by nerzhul** [comment]
Right, i close

**Comment by shinenelson** [comment]
actually, #4 would be the actual feature request of which this is a duplicate of.

( dropping a mention so that this issue can be tracked from that issue in the future )
