### ISSUE TITLE
Update ownCloud SMS with ownCloud Server updates

### ISSUE THREAD

**Issue by enoch85** [nerzhul/ocsms#54]
Today, you have to update ownCloud SMS manually.

It would be much better to get automatic updates, and update when ownCloud comes out with a new release.

FYI It's possible through `ocsid`

**Comment by nerzhul** [comment]
Hi, it's already fixed in master bug not available yet:

https://github.com/nerzhul/ocsms/blob/master/appinfo/info.xml#L11

@martin-rueegg fixed it.

Thanks :)

**Comment by enoch85** [comment]
What would we do without Martin? :)

Med vänlig hälsning
Daniel Hansson

www.en0ch.se

Skickat från Google Nexus 5
Den 18 feb 2015 08:52 skrev "nerzhul" <notifications@github.com>:

**Comment by martin-rueegg** [comment]
tnx, @enoch85 :smile:
