### ISSUE TITLE
No time stamps are added in MySQL

### ISSUE THREAD

**Issue by enoch85** [nerzhul/ocsms#56]
I just noticed that there is no time stamps in MySQL. This will lead to that the SMSes are not in order.

![image](https://cloud.githubusercontent.com/assets/4511254/6259279/3d5f8136-b7d1-11e4-9f32-2e6b27caa92a.png)

Using master-build, and latest Android App.

**Comment by nerzhul** [comment]
The SMS order doesn't use added/lastmodified fields but i'll look at this, another user report this issue.

**Comment by nerzhul** [comment]
Fixed with 98933860e8916443852a5740e790fc28a95e084d
