### ISSUE TITLE
Error	PHP	Undefined offset: 0 at /var/www/owncloud/apps/contacts/lib/backend/shared.php#90

### ISSUE THREAD

**Issue by enoch85** [nerzhul/ocsms#57]
This error shows up in log when getting information about the contacts in ownCloud. Related to ownCloud SMS. I think it could be the photos that trigger this. It spams my log so hard that the server almost stops, and my server is quite powerful. When I deactivate ownCloud SMS the error stops. 

```
Error	PHP	Undefined offset: 0 at /var/www/owncloud/apps/contacts/lib/backend/shared.php#90	2015-02-18T23:53:09+00:00
```

@martin-rueegg Wanna hunt bugs? ;)

**Comment by enoch85** [comment]
Using the latest master btw.

**Comment by nerzhul** [comment]
Hmmmm difficult to know where does it comes from, because it's contact app bug, now ocsms. Have you got the same problem using chat app ?

**Comment by enoch85** [comment]
Nope, get the problem when I use the oCsms app.

**Comment by nerzhul** [comment]
which is your owncloud version and contact app version ?

**Comment by enoch85** [comment]
Latest. I run oC 8.

**Comment by enoch85** [comment]
Maybe @tanghus can answer this?

**Comment by tanghus** [comment]
No idea. Haven't worked on ownCloud since May last year.

**Comment by enoch85** [comment]
Ok. Maybe @jbtbnl have an answer?

**Comment by mokkin** [comment]
I don't have installed ownCloud SMS and I have the same error, actually on oC 8.0.2.

**php -v && apache2 -v && mysql --version && lsb_release -a
PHP 5.5.9-1ubuntu4.7 (cli) (built: Mar 16 2015 20:47:39) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Mar 10 2015 13:05:59
mysql  Ver 14.14 Distrib 5.5.41, for debian-linux-gnu (x86_64) using readline 6.3
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty**

**Comment by martin-rueegg** [comment]
this error should be related to https://github.com/owncloud/contacts/pull/824 which in turn has been fixed and merged. i currently run oC 8.0.2 with Contacts 0.3.0.18 and the patch is applied there. i don't get any errors.
@mokkin could you please verify the Contacts app version (either in index.php/settings/apps or /var/www/owncloud/apps(2)/contacts/appinfo/version) or check if you have the [patch](https://github.com/owncloud/contacts/commit/1642fa5419986c5aa8f9e01a749b040559f3b49f) applied in your version of /var/www/owncloud/apps/contacts/lib/backend/shared.php

**Comment by nerzhul** [comment]
thanks for the information @martin-rueegg

**Comment by mokkin** [comment]
@martin-rueegg 
Unfortunately I cannot help anymore, because I migrated the sever recently to Debian which has also other versions of PHP and Apache.

**Comment by nerzhul** [comment]
After a review this is definitively a oc contact app bug.
