### ISSUE TITLE
phone numbers are not matched with contacts if formatted differently

### ISSUE THREAD

**Issue by bxabi** [nerzhul/ocsms#61]
The contact is matched only if the phone number is formatted exactly as in the sender of the sms. Otherwise the phone number is displayed as sender/receiver, not the contact name.

The sms phone number and the contact phone number should be converted to the same format (no spaces) and then compared to match the Contact.

**Comment by bxabi** [comment]
As I see I also have numbers containing "-" caracters, this should be filtered out too.
Also some numbers have country codes, some not.
I can write a formatter function if you want.

**Comment by nerzhul** [comment]
Hello @bxabi could you give me a proper example, a screen shot.
Don't forget to set your country in the application to dedup contacts

**Comment by bxabi** [comment]
Hi, that's how it looks. I scrambled the numbers a bit :)

![ocsms](https://cloud.githubusercontent.com/assets/11303766/6482843/c8cb2dd0-c26a-11e4-9ede-d797fee0be9c.png)

Most of those numbers are in my contacts just written in forms as +49 123 456789, or +49-123-456789, and they are not matching. I did set the country, but did not help.

**Comment by nerzhul** [comment]
Spaces issues and dashes issues mustn't exist ... we need to review why.
Have you got PHP errors?

**Comment by bxabi** [comment]
![ocsms1](https://cloud.githubusercontent.com/assets/11303766/6482918/aac1cf82-c26b-11e4-8a79-9671abb51502.png)

Actually as you see for this number, the contact is shown above the messages, correctly, but not in the sidebar.

no php errors (where I see them?).

**Comment by nerzhul** [comment]
it seems the international number doesn't match the contact number when generating the contact list.

**Comment by bxabi** [comment]
I updated the owncloud from 8.0.0 to 8.0.2, and made a "git pull" on ocsms, and now the contact names work great, so this looks fixed. Thanks

**Comment by nerzhul** [comment]
Thanks
