### ISSUE TITLE
Controller push method not CSRF protected

### ISSUE THREAD

**Issue by Raydiation** [nerzhul/ocsms#63]
https://github.com/nerzhul/ocsms/blob/master/controller/smscontroller.php#L233

You should in general only use @NoCSRFRequired for the index method.

**Comment by Raydiation** [comment]
Unless its an API method. You should however outsource api methods to a different controller and enable CORS (check the dev docs ;))

**Comment by nerzhul** [comment]
Don't hesitate to create a PR to improve things :)
