### ISSUE TITLE
Clean up bad practices in code

### ISSUE THREAD

**Issue by Raydiation** [nerzhul/ocsms#64]
Some things while reading through the code:
* https://github.com/nerzhul/ocsms/blob/master/appinfo/ocsmsapp.php#L82 : This is called a service locator pattern, do not use it, its an anti pattern. Instead just pass in an object that gets the stuff done for you, e.g. create a ContactService which has this method on it https://github.com/nerzhul/ocsms/blob/master/appinfo/ocsmsapp.php#L94 and pass it into the controller
* https://github.com/nerzhul/ocsms/blob/master/controller/smscontroller.php#L58 :  use OCP\IURLGenerator->linkToRoute('apps.ocsms.page', ['feed' => 'drafts']); 
* https://github.com/nerzhul/ocsms/blob/master/controller/smscontroller.php#L241 : use HTTP error codes instead of your ok flag. By default the 200 status code is set which means OK. 400 means error, you can specify it better by using 404 (not found) etc

**Comment by nerzhul** [comment]
For the second issue it's now fixed. Thanks.

For the first suggestion have you got an example ?
For the codes, i will change that in protocol version 2, but i need to modify android client and do a compatibility layer.

**Comment by Raydiation** [comment]
Yes, you've put logic onto the container/app itself and in your controller you access two methods from it. Put those two methods into a separate class and pass that one into the constructor.

**Comment by Raydiation** [comment]
getContacts and getContactPhotos seem to be the only methods. Put them into a class

**Comment by nerzhul** [comment]
@Raydiation will work on it soon :)

**Comment by nerzhul** [comment]
All is done.
Functions moved to ContactCache in lib/.
URLGenerator changed

For the return codes, not for not, later, yes with protocol v2
