### ISSUE TITLE
How do I translate?

### ISSUE THREAD

**Issue by enoch85** [nerzhul/ocsms#65]
Is this project on Transifex?

@nerzhul

**Comment by enoch85** [comment]
Solved it. 
https://github.com/nerzhul/ownCloud-SMS-App/pull/42
https://github.com/nerzhul/ownCloud-SMS-App/pull/41

**Comment by nerzhul** [comment]
Thanks, read nerzhul/ownCloud-SMS-App#42 for a translation example (or look at the previous serbian PR)
