### ISSUE TITLE
contact lookup and message grouping should ignore extra symbols (such as spaces) in phone no.

### ISSUE THREAD

**Issue by cptMikky** [nerzhul/ocsms#66]
Hi,

the web app treats +111 222 333 444 and +111222333444 as two different numbers/contacts resulting in two separate conversations. One of these formats usually coincides with an existing entry in contact book while the other one remains unresolved. That leads to situations where I have two separate conversations with one contact, one grouped under looked-up contact (i.e. showing the name) and another conversation grouped under phone number only.

This is mostly for inbound and outbound messages - inbounds are non-spaced numbers while outbound are spaced, probably caused by the CM11's stock messaging app.

In any way, spaces and other non-controlling symbols (dashes and slashes for instance) in phone numbers should be ignored and such numbers should be treated as a single number which should then be resolved against Contact book and grouped under single thread/conversation.

cheers,
 -cM.

**Comment by nerzhul** [comment]
This is already the case, but sometimes the parser doesn't resolve it properly. I need to do more investigation to find where is the problem.

**Comment by cptMikky** [comment]
can I help anyhow?

**Comment by nerzhul** [comment]
Question: do you set a country in the application options ?

**Comment by cptMikky** [comment]
No, my country is not in the list - Czech Repulic. What's the purpose of this settings?

**Comment by nerzhul** [comment]
look at lib/countrycode and help us to add the country code :)

**Comment by cptMikky** [comment]
Someone was faster :) 

It's better just a bit in v1.4.4 - the conversation is properly grouped now but it still shows two separate entries in the left panel.

Also, although I do have my country code set properly now, I still get a few messages from different countries. Is this handled somehow? From debugging point of view...

**Comment by nerzhul** [comment]
Have you refreshed the app panel ?

What do you want to know exactly ? The local code is translated to international code and spaces are removed.

**Comment by cptMikky** [comment]
In fact I did a complete fresh installation just to see if there is a difference. What I'm describing is a fresh-start situation.

As for the intl. codes, I was referring to how the country settings affects the app's behaviour. I was reading through phonenumberformatter.php but I'm still not sure I understand what exactly it does. Although reading it again with fresh eyes in the morning I guess I'm getting the idea :) 

And if I got it right, it's not related to this issue since all the affected numbers are already in the intl. format. In fact all numbers I have in my phone book are in intl. format and all incoming calls and messages have also intl. number format already.

**Comment by cengbrecht** [comment]
Hey Nerzhul!

So I have been using it and it works great, syncs, and keeps me safe, but I have noticed that it still has issues trying to group phone numbers together with or without + and - or other symbols like ( ) .

I would like to know if on an update of it, we could force it to run with a cron job, to clean up the database entries so that their numbers are fixed.

Thanks for your work! You're awesome.

Number with + and () and - signs
https://owncloud.brokedcomputer.com/index.php/s/eQGLvlLYXpbNZPA

Number without
https://owncloud.brokedcomputer.com/index.php/s/RwMAQYqj15R7CyQ

**Comment by nerzhul** [comment]
I don't know why this isn't working. The phonenumber cleaner is not very very powerful for everybody as it seems :(. Need to rewrite it, maybe

**Comment by nerzhul** [comment]
Closing this as now it's better
