### ISSUE TITLE
Disapperared?

### ISSUE THREAD

**Issue by delumerlino** [nerzhul/ocsms#69]
Hi,
I have upgraded OC to 8.0.3.
Now Owncloud-sms is disappeared, both from enabled and disabled applications.
It is present under the file system.
I have no strange logs under OC...

**Comment by nerzhul** [comment]
@delumerlino reappeared ? :)

**Comment by delumerlino** [comment]
Yes, but I have always error 9 on Android, no other on the server. Messages
are anyway synced...
Thank you
Il 07/Mag/2015 17:48 "nerzhul" <notifications@github.com> ha scritto:
