### ISSUE TITLE
error while enabling ocms

### ISSUE THREAD

**Issue by mikel392** [nerzhul/ocsms#70]
An exception occurred while executing 'CREATE TABLE `oc_ocsms_config` (`user` VARCHAR(255) NOT NULL, `key` VARCHAR(25555) NOT NULL, `value` VARCHAR(25555) DEFAULT NULL) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1074 Column length too big for column 'key' (max = 21845); use BLOB or TEXT instead  

i'm using mariadb, maybe that's the problem.

**Comment by nerzhul** [comment]
Fixed: https://github.com/nerzhul/ocsms/commit/47a6a86a9509de7bcda6d736b9c6b8160b76cba8
