### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by animalillo** [nerzhul/ocsms#72]
The app syncs the messages with the server, they are displayed in the database, but the user interface is empty.

Also, the dates for added and last modified are "0000-00-00 00:00:00".

Using oc 7.0.4 stable, and looking forward to have time to upgrade to oc 8

**Comment by nerzhul** [comment]
last modified field is unused at this moment.
Can you look at your PHP logs to see if something is wrong please ?

**Comment by animalillo** [comment]
in owncloud logs
>Fatal 	index 	Exception: Contacto no encontrado [404]

**Comment by nerzhul** [comment]
@animalillo this bug is a bug in contact app. Update to owncloud contact app 8.0.3 will solve this

**Comment by animalillo** [comment]
Great, thank you, i've upgraded owncloud and all its apps now to oc8 and it works perfectly

**Comment by nerzhul** [comment]
Thanks for the report
