### ISSUE TITLE
Contacts not showed

### ISSUE THREAD

**Issue by delumerlino** [nerzhul/ocsms#75]
Hi, I am using ocsms for my sms.
My phone contacts are synced with native oc_contacts.
I am not able to see my contacts in conversations list, but only their numbers.
TY

**Comment by nerzhul** [comment]
Hi,
have you selected a country in your ocsms settings ?

**Comment by delumerlino** [comment]
Yes, I have.
The problem is not related to all contacts, but only for some of them..
Il 08/Giu/2015 16:14, "nerzhul" <notifications@github.com> ha scritto:

**Comment by nerzhul** [comment]
Can you check your PHP logs please ? Maybe there is a PHP error somewhere. Please also look at your owncloud logs

**Comment by delumerlino** [comment]
I have no errors in php / apache2.
OC has the transaction error:

Exception: {"Message":"An exception occurred while executing 'DELETE FROM
oc_ocsms_smsdatas WHERE user_id = ? AND sms_id = ?' with params
[\"Andrea\", 10347]:\n\nSQLSTATE[HY000]: General error: 1205 Lock wait
timeout exceeded; try restarting transaction","Code":0,"Trace":"#0
\/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116):
Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception
oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1
\/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php(172):
Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver),
Object(Doctrine\\DBAL\\Driver\\PDOException), 'DELETE FROM oc_...',
Array)\n#2
\/var\/www\/owncloud\/lib\/private\/db\/statementwrapper.php(54):
Doctrine\\DBAL\\Statement->execute(Array)\n#3
\/var\/www\/owncloud\/apps\/ocsms\/db\/smsmapper.php(266):
OC_DB_StatementWrapper->execute(Array)\n#4
\/var\/www\/owncloud\/apps\/ocsms\/controller\/apicontroller.php(103):
OCA\\OcSms\\Db\\SmsMapper->writeToDB('Andrea', Array)\n#5 [internal
function]: OCA\\OcSms\\Controller\\ApiController->push(7564, Array)\n#6
\/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(158):
call_user_func_array(Array, Array)\n#7
\/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(86):
OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\OcSms\\Controller\\ApiController),
'push')\n#8 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(97):
OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\OcSms\\Controller\\ApiController),
'push')\n#9
\/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(44):
OC\\AppFramework\\App::main('ApiController', 'push',
Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#10
[internal function]:
OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#11
\/var\/www\/owncloud\/lib\/private\/route\/router.php(250):
call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler),
Array)\n#12 \/var\/www\/owncloud\/lib\/base.php(782):
OC\\Route\\Router->match('\/apps\/ocsms\/pus...')\n#13
\/var\/www\/owncloud\/index.php(36): OC::handleRequest()\n#14
{main}","File":"\/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":115}

Is there a way to clean the installation (and deleting database tables and
indexes) and start from scratch?

2015-06-08 16:25 GMT+02:00 nerzhul <notifications@github.com>:

> Can you check your PHP logs please ? Maybe there is a PHP error somewhere.
> Please also look at your owncloud logs
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nerzhul/ocsms/issues/75#issuecomment-110013185>.
>



-- 
--------------------------------------------------------------------------
*P *Prima di stampare, pensa all'ambiente ** Think about the environment

**Comment by nerzhul** [comment]
Are you using sqlite ?

**Comment by delumerlino** [comment]
Nope, mysql.

2015-06-09 13:35 GMT+02:00 nerzhul <notifications@github.com>:

> Are you using sqlite ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nerzhul/ocsms/issues/75#issuecomment-110326899>.
>



-- 
--------------------------------------------------------------------------
*P *Prima di stampare, pensa all'ambiente ** Think about the environment

**Comment by nerzhul** [comment]
@delumerlino i see it after in the stack trace, i edited my previous comment on github.

**Comment by delumerlino** [comment]
So what do you suggest? I didn't change anything on mySQL configuration...

**Comment by nerzhul** [comment]
atm i have no idea i'm at work. How many messages do you have in your database ?

**Comment by delumerlino** [comment]
They are about 7k

2015-06-09 14:07 GMT+02:00 nerzhul <notifications@github.com>:

> atm i have no idea i'm at work. How many messages do you have in your
> database ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nerzhul/ocsms/issues/75#issuecomment-110332611>.
>



-- 
--------------------------------------------------------------------------
*P *Prima di stampare, pensa all'ambiente ** Think about the environment

**Comment by nerzhul** [comment]
No many... Then i don't know at this moment, but it seems your PHP instance lost connection to your MySQL instance

**Comment by delumerlino** [comment]
Anyway, oc_sms is the only owncloud app that won't work.
prior to this, I still have Error #9: Server set unhandled HTTP return code.
No way to fix them both??

2015-06-12 17:03 GMT+02:00 nerzhul <notifications@github.com>:

> No many... Then i don't know at this moment, but it seems your PHP
> instance lost connection to your MySQL instance
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nerzhul/ocsms/issues/75#issuecomment-111519766>.
>



-- 
--------------------------------------------------------------------------
*P *Prima di stampare, pensa all'ambiente ** Think about the environment

**Comment by nerzhul** [comment]
The Error #9 generally appears when your server return a 503, or when it wants to upgrade. It's not very easy to interact and the requests on database are very very simple. The main problem is to reproduce your problem. I will study some improvement for protocol handling on Android but it's not very easy to improve and keep the compat. But you have reason, i need to improve the Error #9 to be more precise and maybe detect some owncloud upgrade cases, or another.

**Comment by delumerlino** [comment]
What if I delete the tables from mysql and clean the installation? Is there
a way to start from scratch (without reinstalling oc)?
Il 16/Giu/2015 13:06, "nerzhul" <notifications@github.com> ha scritto:

**Comment by nerzhul** [comment]
I don't think this will fix the problem but you can try.

You should do this: 
- disable ocsms app
- drop tables with *_ocsms_* name
- enable app

**Comment by DJaeger** [comment]
You should also remove all entries of ocsms from oc_appconfig

**Comment by delumerlino** [comment]
Done, but still have the errors...
Il 16/Giu/2015 15:30, "Daniel Jäger" <notifications@github.com> ha scritto:

**Comment by nerzhul** [comment]
It was what i think, but thanks for the test.
@DJaeger was right, but i don't use oc_appconfig for ocsms, only the installation options are into

**Comment by delumerlino** [comment]
Sincerely, I had this error after upgrading php to 5.4....

2015-06-17 10:21 GMT+02:00 nerzhul <notifications@github.com>:

> It was what i think, but thanks for the test.
> @DJaeger <https://github.com/DJaeger> was right, but i don't use
> oc_appconfig for ocsms, only the installation options are into
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nerzhul/ocsms/issues/75#issuecomment-112714405>.
>



-- 
--------------------------------------------------------------------------
*P *Prima di stampare, pensa all'ambiente ** Think about the environment

**Comment by DJaeger** [comment]
That is what I mean.
I had multiple issues on reinstalling or updating apps that were mostly solved by removing the entries from oc_appconfig

**Comment by nerzhul** [comment]
It's possible that oc_appconfig cause problems, it's a owncloud issue not our :(. Closed
