### ISSUE TITLE
Phone and message count oddities

### ISSUE THREAD

**Issue by animalillo** [nerzhul/ocsms#76]
From the same contact i get the phone repeated 4 times, which (i guess is that) makes the message count be repeated many times, so I get 7 messages * 4 exact same phone numbers = 28 messages from the same exact same contact

![Example](http://i.imgur.com/v2i0myG.png)

**Comment by nerzhul** [comment]
Hi,
Thanks for your report, i look at this

**Comment by nerzhul** [comment]
For the duplicated phone numbers can you use this commits and tell me if that fix the first problem please ?

https://github.com/nerzhul/ocsms/commit/a620277d867f14652dc21f3d1e0454a8a7522f66

**Comment by animalillo** [comment]
that commic completely breaks ocsms for me.
>Content Security Policy: Las opciones para esta página han bloqueado la carga de un recurso en self (script-src https://wolfi.es:8080 'unsafe-eval').
>SyntaxError: continue must be inside loop    app.js:209:6
>Error: No module: OcSms     angular.min.js:18:75

**Comment by nerzhul** [comment]
Erf, i do the commit from my phone. I look at this problem on a better server now

**Comment by nerzhul** [comment]
Ok i see it's an issue with the jquery foreach loop

**Comment by nerzhul** [comment]
Okay, look at this commit: 8680ce6d38a280c5207e0a6f7aaefab111d445cd

**Comment by nerzhul** [comment]
Use this instead, sorry :)
https://github.com/nerzhul/ocsms/commit/357e17dfbce5e6807e6f7341cbe3cd731a984762

**Comment by animalillo** [comment]
it works for duplicated phones, now I just get the phone displayed once, but I still have 28 messages as the total count.
(tried latest master and your specified commit)

**Comment by nerzhul** [comment]
@animalillo yes, i didn't fix the message count number. I looked at the code yesterday and i don't see an error in message count. Can you look at your database and see if there are duplicate messages ?

**Comment by animalillo** [comment]
Not any duplicates in my database

**Comment by nerzhul** [comment]
Thanks, i will look at the controller call asap

**Comment by animalillo** [comment]
It's not a big issue, i wouldn't have noticed if the conversation was long xD

**Comment by nerzhul** [comment]
Yes but it's an issue which needs to be fixed, and a reason to have a new release published :)

**Comment by animalillo** [comment]
Ok, I'll be here to test it then :)

**Comment by nerzhul** [comment]
I will work on it before 1.5 release. I need to improve the count interaction with interface since i switch many code to angularJS

**Comment by animalillo** [comment]
:thumbsup:

**Comment by nerzhul** [comment]
The message count is not properly displayed
