### ISSUE TITLE
Scroll issue

### ISSUE THREAD

**Issue by animalillo** [nerzhul/ocsms#77]
When little messages (it's more annoying when there is just one) in a conversation, the first messages gets out of the screen. It's nice in a long conversation that you scroll down to the latest message, but in a short conversation that fits inside the screen, it should be displayed that way, in my opinion.

The problem seems to be that the div containing the comments (app-content-wrapper) it's overlapped with the div displaying the contact details (app-content-header).

**Comment by nerzhul** [comment]
Thanks !
