### ISSUE TITLE
Country list not working on firerfox nightly

### ISSUE THREAD

**Issue by animalillo** [nerzhul/ocsms#79]
When you select the country list in config, on Firefox (41.0a1) nightly on linux it's transparent and disappears after a few seconds, selecting USA, so it becomes unusable.

Probably nothing to do with your app, but guessed you would like to know.
It works correctly on Firefox (38.0) stable linux version.

**Comment by nerzhul** [comment]
@animalillo i think this is a problem with firefox nightly, no problem on many browsers

**Comment by animalillo** [comment]
Yeah, I know, but it was just for you to know

**Comment by nerzhul** [comment]
No problem. I'm using native selects, then the problem is in FF Nightly build. I close the report, thanks to inform me :)
