### ISSUE TITLE
OwnCloud App Activation Problem

### ISSUE THREAD

**Issue by nawrasg** [nerzhul/ocsms#80]
Hi,

First of all, many thanks to this app :)
When I tried to activate it, owncloud showed the following error `no app name specified`!
When I modified the folder name from <b>ocsms-v1.4.5</b> to <b>ocsms</b>, it worked fine.

I hope you update this bug on the owncloud app store.

Regards,

**Comment by nerzhul** [comment]
this bug is not due to ocsms, it's written in the documentation, also in apps.owncloud.com :) I use github tags to generate archive then i cannot change this
