### ISSUE TITLE
Fatal: No SMS shown in Owncloud app 

### ISSUE THREAD

**Issue by mulles** [nerzhul/ocsms#82]
Hi, 

First time that I submit an issue. Did my best too gather all information. Besides I don't get it working it's an pleasure that this kind of features  existed thanks too you on owncloud :) 

**** The Problem:  **** 
**************************

When I navigate to SMS App on owncloud I don't see the uploaded sms messages, but: 

{{ contact.label }}{{ contact.unread > 0 ? ' (' + contact.unread + ') ' : '' }}

Please choose a conversation on the left menu
{{ message.content }}
{{ message.date }}

Any ideas where the problem could be?

**** Information **** 
Server
    ownCloud version: 8.0.4
    PHP versioPHP 5.5.10 n: 
    HTTPd server: 
    HTTPS: e1000.atria.uberspace.de/owncloud/ 

Client

    Android version: 5.1.1.
    Phone: NEXUS 4
    ownCloud SMS app version: 0.18.2 

Content of /owncloud/data/owncloud.log: 

Debug	core	Adding default user backend WEBDAVAUTH.	2015-07-24T19:26:22+00:00
Error	PHP	Trying to get property of non-object at /var/www/virtual/e1000/html/owncloud/lib/private/log/owncloud.php#126	2015-07-24T19:19:12+00:00
Fatal	core	Invalid OCS content returned for app 166059	2015-07-24T19:15:44+00:00
Fatal	core	Invalid OCS content returned for app 168707	2015-07-24T19:15:44+00:00
Fatal	core	Invalid OCS content returned for app 168711	2015-07-24T19:15:44+00:00
Fatal	core	Invalid OCS content returned for app 168708	2015-07-24T19:15:44+00:00
Fatal	core	Invalid OCS content returned for app 166051	2015-07-24T19:15:44+00:00
Fatal	core	Invalid OCS content returned for app 166052	2015-07-24T19:15:44+00:00
Fatal	core	Invalid OCS content returned for app 166056	2015-07-24T19:15:44+00:00
Fatal	core	Invalid OCS content returned for app 166053	2015-07-24T19:15:44+00:00
Fatal	core	Invalid OCS content returned for app 166055	2015-07-24T19:15:44+00:00
Fatal	core	Invalid OCS content returned for app 167289	2015-07-24T19:15:44+00:00
Fatal	core	Invalid OCS content returned for app 166054	2015-07-24T19:15:43+00:00
Fatal	core	Invalid OCS content returned for app 166057	2015-07-24T19:15:43+00:00
Error	PHP	Invalid argument supplied for foreach() at /var/www/virtual/e1000/html/owncloud/lib/private/app.php#1233	2015-07-24T19:15:43+00:00

**Comment by nerzhul** [comment]
you have a browser issue because angularJS doesn't work. What is your browser ? Can look at JS console ?

**Comment by mulles** [comment]
Thanks, problem solved. 

Solutions for others: 

The rights for the owncloud folder "ocsms" were wrong. I changed them with the command: 
 "chmod 755 ocsms"
 to the same rights the other owncloud apps do have.

Incredible support ;) and amazing app, pleased that I can use it now :) Is it possible to resync messages back to the phone (after factory reset)/new phone? Shall/can I open a feature request for that?

**Comment by nerzhul** [comment]
oh it's a right problem, i see :)
For the message restoration it's a feature in progress but i need some time to do it properly. I have started to talk with ocsms server, now i need to add conversation support client side to check messages to restore.
Thanks for the report
