### ISSUE TITLE
Alternative install method

### ISSUE THREAD

**Issue by quizilkend** [nerzhul/ocsms#83]
Hey!

I'd really like to try your work, as it sounds very promising.
Unfortunately I have no GApps at all on my Android mobile phone and the version on FDroid isn't working properly (account creation fails).
I am totally willingly to pay or donate, but don't have the ability to purchase the app via PlayStore.

Is there maybe a solution?
Best wishes,
Sammy

**Comment by mulles** [comment]
you can download the app via the f droid website: 

https://f-droid.org/repo/fr.unix_experience.owncloud_sms_27.apk

But as you may know you need to enable "install unknown sources". 

For other versions go to https://f-droid.org/repository/browse/?fdfilter=ocsms&fdid=fr.unix_experience.owncloud_sms

**Comment by quizilkend** [comment]
Thanks for your advice, but the F-Droid version isn't working for me. I think, because I use a self-signed certificate.

**Comment by DJaeger** [comment]
The behaviour of the app in GPlay and F-Droid is the same.
And in general they work like expected.
You shou create an issue in the correct repo (for the Android app) and supply some more infos like the error message and a logcat:
https://github.com/nerzhul/ownCloud-SMS-App/issues

**Comment by DJaeger** [comment]
Before you create a new issue please try to add the certificate to your keychain.
For this you can use the following app:
CAdroid (Certificate importer) - https://f-droid.org/app/at.bitfire.cadroid

@nerzhul: There should be some more info in the app if certificate is not accepted, possibly with reference to the mentioned app.

**Comment by nerzhul** [comment]
@DJaeger you talk about HTTPS in the app ?

**Comment by animalillo** [comment]
Maybe add a checkbox to allow untrusted certificates?

**Comment by nerzhul** [comment]
@animalillo in fact the problem atm is that the SSL check is performed by owncloud-client and i didn't see options to validate or not certificates, it's why the google play store app has a patched owncloud-client to disable this verification on self-signed.

**Comment by DJaeger** [comment]
@nerzhul: yes.
Sorry I was not aware, that its another edition in GPlay.
Why not apply the same patch to the sources?

**Comment by nerzhul** [comment]
@DJaeger because owncloud-client is a dependancy, not provided by me, but by owncloud itself and F-Droid use the real dep

**Comment by DJaeger** [comment]
Where can your modified version of oc-lib can be found?
If you would supply it, the building of F-Droid could be changed to use it.

**Comment by nerzhul** [comment]
it's only on my PC and not updated , need some modifications. Maybe in the future i will remove many parts of the lib to use only the essential connector

**Comment by DJaeger** [comment]
Why not make a PR to the libs origin?

**Comment by nerzhul** [comment]
Not related to this repository
