### ISSUE TITLE
Can't install the web app on my server

### ISSUE THREAD

**Issue by vbelloir** [nerzhul/ocsms#84]
Hi all,
Server
    ownCloud version: 8.1
    PHP version: 5.5.26
    HTTPd server: Server version: Apache/2.2.29
    HTTPS: yes, with certificate startssl

Client
    Android version: 4.2.2
    Phone: Wiko Cink Peax
    ownCloud SMS app version: 0.18.5 (F-droid)

Content of /owncloud/data/owncloud.log
At this step, I don't think the log is useful.
I downloaded the latest release from https://github.com/nerzhul/ocsms/releases
The archive is uncompressed in the owncloud/apps/ocsms directory.
But I can't see it in https://my-domain/index.php/settings/apps?installed

Can you help me?
 Thanks.
Vincent

**Comment by vbelloir** [comment]
This is the first time I install an webapp from an archive. 
I have just tried to install another one (this one : https://apps.owncloud.com/content/show.php/Storage+Charts+2?content=165528), and it works, I was able to activate it.

Maybe I am doing something wrong, but I don't know what.

**Comment by vbelloir** [comment]
Arf, sorry, the issue is still open.

**Comment by nerzhul** [comment]
Is the app directly on apps/ocsms, there is no new subdir ?

**Comment by vbelloir** [comment]
Yes, directly in apps/owncloud

**Comment by nerzhul** [comment]
i see you are french, we can talk in french if you want.
You didn't see app with an admin capable to enable it ?

**Comment by vbelloir** [comment]
Yes, I'm french but we can continue in english, It can help more people.

No, I can't see the app in the web interface. 
I tried to install another app (storage Chart 2), and it works : 
![plop](https://cloud.githubusercontent.com/assets/13942805/9563550/ab61d0b0-4e87-11e5-81e4-4bbf8cf410c2.jpg)

But with ocsms, I can't find it, in none of the categories.

I tried with a standard user, and a admin user, without success.

**Comment by nerzhul** [comment]
Ocsms is in experimental if i remember.
Also don't forget when you use the archive from github to rename folder from ocsms-<version> to ocsms, please read installation instructions :)

**Comment by vbelloir** [comment]
Yes, I kow that ocsms is experimental. I'm not sure I will use it, but I wan to try this app if possible.

As you can see is the picture of message 5 days ago, the ocsms-xxx was rename in ocsms : 
![2938c600-4b4b-11e5-80bf-e883c0e22903](https://cloud.githubusercontent.com/assets/13942805/9566273/4a1c4308-4eff-11e5-8964-b6dd3d440922.jpg)

Your help is appreciate, but I do read the installation instructions.

**Comment by nerzhul** [comment]
no i don't said ocsms is experimental, but it's in the experimental new section of owncloud repo (8.1).
i don't understand why it's not showing up in your installation, how can this be possible to don't see the app if it's installed...

**Comment by vbelloir** [comment]
Ok,, as I found it in the Multimedia section in https://apps.owncloud.com/content/show.php/ownCloud+SMS?content=167289

I was expected to find it in the multimedia category in my owncloud web interface.

What should be the right permission of the ocsms files and folder?

**Comment by nerzhul** [comment]
@vbelloir no problem.
App doesn't need httpd rights on folders. It's a pure SQL backend. You can set 644/755 on files/folder and give them to root:root / root:wheel

**Comment by DJaeger** [comment]
@vbelloir: Is this solved?

**Comment by vbelloir** [comment]
@DJaeger : yes, installing through git clone was OK for me.

**Comment by DJaeger** [comment]
@vbelloir: Then please close this issue. Thanks.
