### ISSUE TITLE
Can't install on a fresh install of OC 8.1.1 (stable)

### ISSUE THREAD

**Issue by lakano** [nerzhul/ocsms#85]
Hello,

I'm trying to install your app (seems to be really useful, thanks for your time!) 

But unfortunately, when I enable it in the Experimental applications store, it's only create an empty ocsms/ folder.

Then, if I'm trying to put your v1.5 version inside (and to set www-data rights), OC stop to works with a screen to request a migration need to be done to 8.1.1 (but it's already the current version).
In the same time, all others URL & services are down.

If I remove the files inside the ocsms/ folder, and refresh the OC page, this fix the problem.

But if I'm trying to keep the ocsms/ files and to accept to upgrade to 8.1.1 ... this crash totally my OC.
I've been reinstall from scratch OC after that.

So, may be your plugin it's not compatible with OC 8.1.1 ?

BTW, your plugin is it compatible with all PHP versions ? ( significant breaking changes since 5.6 )
( firstly tester with 5.6, then I've expected this could be a bug with this PHP version, then I've downgraded to 5.5.9... but it's the same problem )

Regards,

**Comment by nerzhul** [comment]
Hi, i'm running ocsms on a owncloud 8.1.1 with Apache 2.4 and PHP 5.6 on my server and it's running fine.
Can you look at owncloud.log + apache error logs ?

**Comment by lakano** [comment]
Hello,

Just retried, there is no new lines in data/owncloud.log and nothing in my NginX error.log
( excepted new lines of owncloud about no update for other apps )

I precise I've set the loglevel to 0 ( = DEBUG ).

I'm under Ubuntu Server 14.04.1 / NginX 1.4.6 / OwnCloud 8.1.1 / OCSMS 1.5 / PHP 5.6.12

Once again, I have the blue screen (of the death ^^) of OwnCloud that ask me to upgrade to 8.1.1, whatever the page of OwnCloud I use.

If I remove all files in apps/ocsms/ and reload, OwnCloud works.

Regards,

**Comment by nerzhul** [comment]
The upgrade screen should be done when you install owncloud SMS because database scheme must be upgraded

**Comment by lakano** [comment]
Ok, I don't known the reason, but last time I've accepted this blue screen after activated OCSMS this have broken my OwnCloud... 

Now it's works :)
