### ISSUE TITLE
Synchronization intervals and connections not respected

### ISSUE THREAD

**Issue by zubrick** [nerzhul/ocsms#86]
I have set ocsms to synchronize only evey 24 hours and only on wifi, but it keeps synchronizing all the time even on mobile data.
I have 240MB of data transfer last month for only a dozen of sms...

Phone: 
Sony Xperia Z3 compact. OS and app to last version

Server: 
ownCloud SMS  1.4.5
ownCloud 8.1.1 (installed using apt)
Debian Wheezy

**Comment by nerzhul** [comment]
hi @zubrick is this synchronise or push on receive ?

**Comment by zubrick** [comment]
only synchronise over wifi is checked. 
I didn't notice the push on receive option, it's what I need so I will try it, but it doesn't solve the issue

**Comment by zubrick** [comment]
Ok, so, changing to push on receive didn't change the behavior, it still synchronizes all the time.
So now, I have only push on receive checked and frequency set to never.
I tried to remove the account and recreate it, but still the same.

**Comment by nerzhul** [comment]
@zubrick thanks for the troubleshoot.

**Comment by nerzhul** [comment]
@zubrick fixed in ownCloud-SMS-App/commit/c72a897f8199a2e3a1e3e94a44688e7a98e7f1c1

**Comment by nerzhul** [comment]
A release will be done when i finished the refactor on the android app
