### ISSUE TITLE
How to export uploaded sms from ocsms?

### ISSUE THREAD

**Issue by wtayyeb** [nerzhul/ocsms#87]
Hi,

I have to reset factory my phone and I was using ocsms! not I want them back to my phone. as I see ocsms not doing it.. so how can I export them from ocsms.owncloud?

**Comment by nerzhul** [comment]
hi @wtayyeb the importation is in progress, look this is the last commit on this subject:

https://github.com/nerzhul/ownCloud-SMS-App/commit/1a6feec7eef52341189c53f22524c845e4912db9

It takes some times because i'm working on this to add some more informations.

**Comment by nerzhul** [comment]
This is now fixed, please upgrade server to 1.11.0 at least and wait for android app 0.33.0 to restore them
