### ISSUE TITLE
Notification settings

### ISSUE THREAD

**Issue by skjnldsv** [nerzhul/ocsms#89]
Hi! 
Thanks for your awesome work.
I would like to suggest an addition to the settings:
- Disable notifications
- Enable notifications for incoming texts only (Right now I get notif for received AND sent sms)
- Enable for both (like it is right now)

Thanks again! ;)

**Comment by nerzhul** [comment]
Hi @skjnldsv sorry for to be very very slow.
I will work on it, first to disable notifications. I agree notification for sent sms is a little bit useless, will look at my old notification code to see if there is a more portable way to do this using angular js, maybe. But first settings :)

**Comment by nerzhul** [comment]
Issue solved in master. thanks for the idea

**Comment by skjnldsv** [comment]
@nerzhul Don't be! :)
Glad I could help!
