### ISSUE TITLE
Option to Limit SMS shown per page 

### ISSUE THREAD

**Issue by p91** [nerzhul/ocsms#90]
Hi,

first of all, thank you very much for this app.
Unfortunately, I have some problems with very long conversations (>3000 SMS).
The scripts used freeze my firefox for about 2-3 minutes every time I visit the page.

Could we have an options to display the last x SMS in the conversation? Let x=500 as the default and if someone needs older SMS he can just click "next page" or scroll up and the next messages can be loaded in the background ore something.

With best regards,

p91

(I guess this should be marked as an enhancement but I cannot see any way to mark it like that)

**Comment by nerzhul** [comment]
@p91 angularJS is a little bit problematic. A such option could be useful, i need some time to look at angular best practices for this

**Comment by nerzhul** [comment]
Fixed in master branch, added a setting.
