### ISSUE TITLE
No app name specified

### ISSUE THREAD

**Issue by krisken** [nerzhul/ocsms#91]
I've installed the newest version of owncloud.  When I want to add the application (activate it), i get the error "No app name specified" when I click on "install".  I can't do anything further.

**Comment by krisken** [comment]
ownCloud version: 8.2.1
    PHP version: 5.4.45
    HTTPd server: Apache 2.2.31
    HTTPS: cloud.krisa.be

**Comment by nerzhul** [comment]
did you renamed the folder to ocsms ?
