### ISSUE TITLE
No visible sync

### ISSUE THREAD

**Issue by satou-kun** [nerzhul/ocsms#93]
Apparently the web app and the android app have been installed successfully, without error messages.

The sync seems to work (I can see briefly the message "syncing in process") but in fact no message have been synced at all as I can see when I log on the server. I can only see the test messages.

Spec: owncloud 8.2 (archlinux)
webapp: v1.5.0
app: ocsms 0.18.5 from fdroid

**Comment by satou-kun** [comment]
Answer: I use a different SMS app and the database on the phone is not the same. :(

**Comment by nerzhul** [comment]
@satou-kun exact, sorry
