### ISSUE TITLE
Issue on latest OC

### ISSUE THREAD

**Issue by StopTrain** [nerzhul/ocsms#94]
Did some testing with this and found that even after I've read all messages, I log out and back in, it shows everything as new again.

I've also noticed this error in my logs:

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO oc_ocsms_smsdatas (user_id, added, lastmodified, sms_flags, sms_date, sms_id,sms_address, sms_msg, sms_mailbox, sms_type) VALUES (?,?,?,?,?,?,?,?,?,?)' with params ["dominian", "2016-01-28 03:10:26", "2016-01-28 03:10:26", "11", "1452831149624", 79, "8123451475", "Yeah she's a cutie \ud83d\ude0a", 1, 2]: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x98\x8A' for column 'sms_msg' at row 1

This was fixed by finding the function doing the insert for the body of the sms message and using a utf8 convert function.  That got it working, however, the issue previously mentioned of 'unread' messages still persists

Thank you!

**Comment by nerzhul** [comment]
i'm french and i'm using UTF8 database, i think the problem is mainly on your database, not in ocsms

**Comment by StopTrain** [comment]
Hmm and that could be, with regards to the database.  I'll look into that, but not had any issues with anything else so who knows.

What about the other question about read messages showing unread after I've logged out/logged back in, or just reloading the SMS app?   Example: I go to FIles, then come back to SMS, it shows them all as unread again.

**Comment by nerzhul** [comment]
@StopTrain can you open an issue for this problem, i will look at this when i get some time, maybe this weekend :)

**Comment by StopTrain** [comment]
Of course!  I'll close this and open a new issue.  Thank you for the prompt responses.
