### ISSUE TITLE
Blank page syntax error, unexpected '[' at smscontroller.php#59

### ISSUE THREAD

**Issue by mcepl** [nerzhul/ocsms#98]
When enabling ocsms on owncloud owncloud-7.0.12-1.el6.noarch (RHEL-6, packages from Fedora EPEL) with PHP 5.3.3 I got this error when switching to SMS app as normal user (installation went without a problem, seemingly):
```
{"app":"PHP","message":"syntax error, unexpected '[' at \/srv\/owncloud\/apps\/ocsms\/controller\/smscontroller.php#59","level":3,"time":"2016-02-08T16:42:30+00:00"}
```
and webpage is completely blank, only web console in Firefox reports error 500.

**Comment by nerzhul** [comment]
mcepi you should use PHP 5.4 at least . PHP 5.3 isn't supported anymore

**Comment by mcepl** [comment]
Can I plead for mercy here? ``php 5.3`` is what's installed on the plain RHEL-6, and Fedora people managed to keep [OwnCloud 7 working on it](https://bodhi.fedoraproject.org/updates/?packages=owncloud). I was mighty encouraged when I saw that you still support OC7, so I hoped that I could use it. Unfortunately, it is unlikely that I would break this system and run from unsupported third party packages for php and owncloud just because of your app.

**Comment by nerzhul** [comment]
@mcepl which release do you use ? Maybe i can look at this, but PHP 5.3 is old and not covered by security fixes

**Comment by mcepl** [comment]
``php-5.3.3-46.el6_6.x86_64`` is the official PHP on RHEL-6

**Comment by nerzhul** [comment]
5.3 is EOL, i cannot support it anymore

http://php.net/supported-versions.php
