### ISSUE TITLE
Can not activate server app on OC 8.2.2

### ISSUE THREAD

**Issue by stefan-niedermann** [nerzhul/ocsms#99]
Error message: `Das Archiv enthält kein Verzeichnis mit dem Namen ocsms`
Translation: "The archive does not contain a directory with the name ocsms"

**Comment by nerzhul** [comment]
@stefan-niedermann ensure there is ocsms not ocsms-master in your apps folder

**Comment by stefan-niedermann** [comment]
Well, tried to install it from the built-in ownCloud "App-Store" - i guess other people should have the same problems...

**Comment by nerzhul** [comment]
yes; the appstore integration with github is not very good :(

**Comment by nerzhul** [comment]
@stefan-niedermann issue is now fixed on playstore
